run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  path-prefix: ""

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gocyclo
    - gocritic
    - gosec
    - misspell
    - revive
    - typecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    exclude-functions:
      - (net/http.ResponseWriter).Write
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/mlgaray/ecommerce_api
  
  goconst:
    min-len: 3
    min-occurrences: 2
  
  gocyclo:
    min-complexity: 10
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true
      - name: var-naming
        disabled: false
  
  gosec:
    excludes:
      - G101 # Hardcoded credentials (for error message constants)
      - G107 # HTTP request to variable URL (for integration tests)
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input

issues:
  exclude-dirs:
    - vendor
    - mocks
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - goconst
    - path: main\.go
      linters:
        - revive
  
  max-issues-per-linter: 0
  max-same-issues: 0