// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewAuthHandler creates a new instance of AuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthHandler {
	mock := &AuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthHandler is an autogenerated mock type for the AuthHandler type
type AuthHandler struct {
	mock.Mock
}

type AuthHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthHandler) EXPECT() *AuthHandler_Expecter {
	return &AuthHandler_Expecter{mock: &_m.Mock}
}

// SignIn provides a mock function for the type AuthHandler
func (_mock *AuthHandler) SignIn(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// AuthHandler_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type AuthHandler_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthHandler_Expecter) SignIn(w interface{}, r interface{}) *AuthHandler_SignIn_Call {
	return &AuthHandler_SignIn_Call{Call: _e.mock.On("SignIn", w, r)}
}

func (_c *AuthHandler_SignIn_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthHandler_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHandler_SignIn_Call) Return() *AuthHandler_SignIn_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthHandler_SignIn_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *AuthHandler_SignIn_Call {
	_c.Run(run)
	return _c
}

// SignUp provides a mock function for the type AuthHandler
func (_mock *AuthHandler) SignUp(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// AuthHandler_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type AuthHandler_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthHandler_Expecter) SignUp(w interface{}, r interface{}) *AuthHandler_SignUp_Call {
	return &AuthHandler_SignUp_Call{Call: _e.mock.On("SignUp", w, r)}
}

func (_c *AuthHandler_SignUp_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthHandler_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHandler_SignUp_Call) Return() *AuthHandler_SignUp_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthHandler_SignUp_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *AuthHandler_SignUp_Call {
	_c.Run(run)
	return _c
}
