// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewCategoryService creates a new instance of CategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryService {
	mock := &CategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoryService is an autogenerated mock type for the CategoryService type
type CategoryService struct {
	mock.Mock
}

type CategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryService) EXPECT() *CategoryService_Expecter {
	return &CategoryService_Expecter{mock: &_m.Mock}
}

// CountByShopIDWithFilters provides a mock function for the type CategoryService
func (_mock *CategoryService) CountByShopIDWithFilters(ctx context.Context, shopID int, filters models.CategoryFilters) (int, error) {
	ret := _mock.Called(ctx, shopID, filters)

	if len(ret) == 0 {
		panic("no return value specified for CountByShopIDWithFilters")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.CategoryFilters) (int, error)); ok {
		return returnFunc(ctx, shopID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.CategoryFilters) int); ok {
		r0 = returnFunc(ctx, shopID, filters)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.CategoryFilters) error); ok {
		r1 = returnFunc(ctx, shopID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryService_CountByShopIDWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByShopIDWithFilters'
type CategoryService_CountByShopIDWithFilters_Call struct {
	*mock.Call
}

// CountByShopIDWithFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - filters models.CategoryFilters
func (_e *CategoryService_Expecter) CountByShopIDWithFilters(ctx interface{}, shopID interface{}, filters interface{}) *CategoryService_CountByShopIDWithFilters_Call {
	return &CategoryService_CountByShopIDWithFilters_Call{Call: _e.mock.On("CountByShopIDWithFilters", ctx, shopID, filters)}
}

func (_c *CategoryService_CountByShopIDWithFilters_Call) Run(run func(ctx context.Context, shopID int, filters models.CategoryFilters)) *CategoryService_CountByShopIDWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.CategoryFilters
		if args[2] != nil {
			arg2 = args[2].(models.CategoryFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CategoryService_CountByShopIDWithFilters_Call) Return(n int, err error) *CategoryService_CountByShopIDWithFilters_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CategoryService_CountByShopIDWithFilters_Call) RunAndReturn(run func(ctx context.Context, shopID int, filters models.CategoryFilters) (int, error)) *CategoryService_CountByShopIDWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type CategoryService
func (_mock *CategoryService) Create(ctx context.Context, category *models.Category, imageBuffer []byte, shopID int) (*models.Category, error) {
	ret := _mock.Called(ctx, category, imageBuffer, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Category, []byte, int) (*models.Category, error)); ok {
		return returnFunc(ctx, category, imageBuffer, shopID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Category, []byte, int) *models.Category); ok {
		r0 = returnFunc(ctx, category, imageBuffer, shopID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Category, []byte, int) error); ok {
		r1 = returnFunc(ctx, category, imageBuffer, shopID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CategoryService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *models.Category
//   - imageBuffer []byte
//   - shopID int
func (_e *CategoryService_Expecter) Create(ctx interface{}, category interface{}, imageBuffer interface{}, shopID interface{}) *CategoryService_Create_Call {
	return &CategoryService_Create_Call{Call: _e.mock.On("Create", ctx, category, imageBuffer, shopID)}
}

func (_c *CategoryService_Create_Call) Run(run func(ctx context.Context, category *models.Category, imageBuffer []byte, shopID int)) *CategoryService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Category
		if args[1] != nil {
			arg1 = args[1].(*models.Category)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CategoryService_Create_Call) Return(category1 *models.Category, err error) *CategoryService_Create_Call {
	_c.Call.Return(category1, err)
	return _c
}

func (_c *CategoryService_Create_Call) RunAndReturn(run func(ctx context.Context, category *models.Category, imageBuffer []byte, shopID int) (*models.Category, error)) *CategoryService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type CategoryService
func (_mock *CategoryService) Delete(ctx context.Context, categoryID int, shopID int) error {
	ret := _mock.Called(ctx, categoryID, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, categoryID, shopID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CategoryService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CategoryService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID int
//   - shopID int
func (_e *CategoryService_Expecter) Delete(ctx interface{}, categoryID interface{}, shopID interface{}) *CategoryService_Delete_Call {
	return &CategoryService_Delete_Call{Call: _e.mock.On("Delete", ctx, categoryID, shopID)}
}

func (_c *CategoryService_Delete_Call) Run(run func(ctx context.Context, categoryID int, shopID int)) *CategoryService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CategoryService_Delete_Call) Return(err error) *CategoryService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CategoryService_Delete_Call) RunAndReturn(run func(ctx context.Context, categoryID int, shopID int) error) *CategoryService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByShopIDWithFilters provides a mock function for the type CategoryService
func (_mock *CategoryService) GetAllByShopIDWithFilters(ctx context.Context, shopID int, filters models.CategoryFilters) ([]*models.Category, error) {
	ret := _mock.Called(ctx, shopID, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByShopIDWithFilters")
	}

	var r0 []*models.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.CategoryFilters) ([]*models.Category, error)); ok {
		return returnFunc(ctx, shopID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.CategoryFilters) []*models.Category); ok {
		r0 = returnFunc(ctx, shopID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.CategoryFilters) error); ok {
		r1 = returnFunc(ctx, shopID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryService_GetAllByShopIDWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByShopIDWithFilters'
type CategoryService_GetAllByShopIDWithFilters_Call struct {
	*mock.Call
}

// GetAllByShopIDWithFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - filters models.CategoryFilters
func (_e *CategoryService_Expecter) GetAllByShopIDWithFilters(ctx interface{}, shopID interface{}, filters interface{}) *CategoryService_GetAllByShopIDWithFilters_Call {
	return &CategoryService_GetAllByShopIDWithFilters_Call{Call: _e.mock.On("GetAllByShopIDWithFilters", ctx, shopID, filters)}
}

func (_c *CategoryService_GetAllByShopIDWithFilters_Call) Run(run func(ctx context.Context, shopID int, filters models.CategoryFilters)) *CategoryService_GetAllByShopIDWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.CategoryFilters
		if args[2] != nil {
			arg2 = args[2].(models.CategoryFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CategoryService_GetAllByShopIDWithFilters_Call) Return(categorys []*models.Category, err error) *CategoryService_GetAllByShopIDWithFilters_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *CategoryService_GetAllByShopIDWithFilters_Call) RunAndReturn(run func(ctx context.Context, shopID int, filters models.CategoryFilters) ([]*models.Category, error)) *CategoryService_GetAllByShopIDWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type CategoryService
func (_mock *CategoryService) GetByID(ctx context.Context, categoryID int) (*models.Category, error) {
	ret := _mock.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Category, error)); ok {
		return returnFunc(ctx, categoryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Category); ok {
		r0 = returnFunc(ctx, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CategoryService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID int
func (_e *CategoryService_Expecter) GetByID(ctx interface{}, categoryID interface{}) *CategoryService_GetByID_Call {
	return &CategoryService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, categoryID)}
}

func (_c *CategoryService_GetByID_Call) Run(run func(ctx context.Context, categoryID int)) *CategoryService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryService_GetByID_Call) Return(category *models.Category, err error) *CategoryService_GetByID_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *CategoryService_GetByID_Call) RunAndReturn(run func(ctx context.Context, categoryID int) (*models.Category, error)) *CategoryService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type CategoryService
func (_mock *CategoryService) Update(ctx context.Context, categoryID int, category *models.Category, newImageBuffer []byte, shopID int) error {
	ret := _mock.Called(ctx, categoryID, category, newImageBuffer, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.Category, []byte, int) error); ok {
		r0 = returnFunc(ctx, categoryID, category, newImageBuffer, shopID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CategoryService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CategoryService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID int
//   - category *models.Category
//   - newImageBuffer []byte
//   - shopID int
func (_e *CategoryService_Expecter) Update(ctx interface{}, categoryID interface{}, category interface{}, newImageBuffer interface{}, shopID interface{}) *CategoryService_Update_Call {
	return &CategoryService_Update_Call{Call: _e.mock.On("Update", ctx, categoryID, category, newImageBuffer, shopID)}
}

func (_c *CategoryService_Update_Call) Run(run func(ctx context.Context, categoryID int, category *models.Category, newImageBuffer []byte, shopID int)) *CategoryService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.Category
		if args[2] != nil {
			arg2 = args[2].(*models.Category)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *CategoryService_Update_Call) Return(err error) *CategoryService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CategoryService_Update_Call) RunAndReturn(run func(ctx context.Context, categoryID int, category *models.Category, newImageBuffer []byte, shopID int) error) *CategoryService_Update_Call {
	_c.Call.Return(run)
	return _c
}
