// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

type CategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryRepository) EXPECT() *CategoryRepository_Expecter {
	return &CategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) Create(ctx context.Context, category *models.Category, shopID int) (*models.Category, error) {
	ret := _mock.Called(ctx, category, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Category, int) (*models.Category, error)); ok {
		return returnFunc(ctx, category, shopID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Category, int) *models.Category); ok {
		r0 = returnFunc(ctx, category, shopID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Category, int) error); ok {
		r1 = returnFunc(ctx, category, shopID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *models.Category
//   - shopID int
func (_e *CategoryRepository_Expecter) Create(ctx interface{}, category interface{}, shopID interface{}) *CategoryRepository_Create_Call {
	return &CategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category, shopID)}
}

func (_c *CategoryRepository_Create_Call) Run(run func(ctx context.Context, category *models.Category, shopID int)) *CategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Category
		if args[1] != nil {
			arg1 = args[1].(*models.Category)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CategoryRepository_Create_Call) Return(category1 *models.Category, err error) *CategoryRepository_Create_Call {
	_c.Call.Return(category1, err)
	return _c
}

func (_c *CategoryRepository_Create_Call) RunAndReturn(run func(ctx context.Context, category *models.Category, shopID int) (*models.Category, error)) *CategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
