// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/cloudinary/cloudinary-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewCloudinaryConnection creates a new instance of CloudinaryConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudinaryConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudinaryConnection {
	mock := &CloudinaryConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CloudinaryConnection is an autogenerated mock type for the CloudinaryConnection type
type CloudinaryConnection struct {
	mock.Mock
}

type CloudinaryConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *CloudinaryConnection) EXPECT() *CloudinaryConnection_Expecter {
	return &CloudinaryConnection_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type CloudinaryConnection
func (_mock *CloudinaryConnection) Connect() *cloudinary.Cloudinary {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 *cloudinary.Cloudinary
	if returnFunc, ok := ret.Get(0).(func() *cloudinary.Cloudinary); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudinary.Cloudinary)
		}
	}
	return r0
}

// CloudinaryConnection_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type CloudinaryConnection_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *CloudinaryConnection_Expecter) Connect() *CloudinaryConnection_Connect_Call {
	return &CloudinaryConnection_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *CloudinaryConnection_Connect_Call) Run(run func()) *CloudinaryConnection_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CloudinaryConnection_Connect_Call) Return(cloudinary1 *cloudinary.Cloudinary) *CloudinaryConnection_Connect_Call {
	_c.Call.Return(cloudinary1)
	return _c
}

func (_c *CloudinaryConnection_Connect_Call) RunAndReturn(run func() *cloudinary.Cloudinary) *CloudinaryConnection_Connect_Call {
	_c.Call.Return(run)
	return _c
}
