// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cloudinary/cloudinary-go/v2/api/uploader"
	mock "github.com/stretchr/testify/mock"
)

// NewCloudinary creates a new instance of Cloudinary. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudinary(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cloudinary {
	mock := &Cloudinary{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cloudinary is an autogenerated mock type for the Cloudinary type
type Cloudinary struct {
	mock.Mock
}

type Cloudinary_Expecter struct {
	mock *mock.Mock
}

func (_m *Cloudinary) EXPECT() *Cloudinary_Expecter {
	return &Cloudinary_Expecter{mock: &_m.Mock}
}

// Destroy provides a mock function for the type Cloudinary
func (_mock *Cloudinary) Destroy(ctx context.Context, params uploader.DestroyParams) (*uploader.DestroyResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 *uploader.DestroyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploader.DestroyParams) (*uploader.DestroyResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploader.DestroyParams) *uploader.DestroyResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uploader.DestroyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploader.DestroyParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cloudinary_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type Cloudinary_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - params uploader.DestroyParams
func (_e *Cloudinary_Expecter) Destroy(ctx interface{}, params interface{}) *Cloudinary_Destroy_Call {
	return &Cloudinary_Destroy_Call{Call: _e.mock.On("Destroy", ctx, params)}
}

func (_c *Cloudinary_Destroy_Call) Run(run func(ctx context.Context, params uploader.DestroyParams)) *Cloudinary_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploader.DestroyParams
		if args[1] != nil {
			arg1 = args[1].(uploader.DestroyParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cloudinary_Destroy_Call) Return(destroyResult *uploader.DestroyResult, err error) *Cloudinary_Destroy_Call {
	_c.Call.Return(destroyResult, err)
	return _c
}

func (_c *Cloudinary_Destroy_Call) RunAndReturn(run func(ctx context.Context, params uploader.DestroyParams) (*uploader.DestroyResult, error)) *Cloudinary_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type Cloudinary
func (_mock *Cloudinary) Upload(ctx context.Context, file interface{}, uploadParams uploader.UploadParams) (*uploader.UploadResult, error) {
	ret := _mock.Called(ctx, file, uploadParams)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *uploader.UploadResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, uploader.UploadParams) (*uploader.UploadResult, error)); ok {
		return returnFunc(ctx, file, uploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, uploader.UploadParams) *uploader.UploadResult); ok {
		r0 = returnFunc(ctx, file, uploadParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uploader.UploadResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, uploader.UploadParams) error); ok {
		r1 = returnFunc(ctx, file, uploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cloudinary_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type Cloudinary_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - file interface{}
//   - uploadParams uploader.UploadParams
func (_e *Cloudinary_Expecter) Upload(ctx interface{}, file interface{}, uploadParams interface{}) *Cloudinary_Upload_Call {
	return &Cloudinary_Upload_Call{Call: _e.mock.On("Upload", ctx, file, uploadParams)}
}

func (_c *Cloudinary_Upload_Call) Run(run func(ctx context.Context, file interface{}, uploadParams uploader.UploadParams)) *Cloudinary_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 uploader.UploadParams
		if args[2] != nil {
			arg2 = args[2].(uploader.UploadParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cloudinary_Upload_Call) Return(uploadResult *uploader.UploadResult, err error) *Cloudinary_Upload_Call {
	_c.Call.Return(uploadResult, err)
	return _c
}

func (_c *Cloudinary_Upload_Call) RunAndReturn(run func(ctx context.Context, file interface{}, uploadParams uploader.UploadParams) (*uploader.UploadResult, error)) *Cloudinary_Upload_Call {
	_c.Call.Return(run)
	return _c
}
