// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewCouponHandler creates a new instance of CouponHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCouponHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *CouponHandler {
	mock := &CouponHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CouponHandler is an autogenerated mock type for the CouponHandler type
type CouponHandler struct {
	mock.Mock
}

type CouponHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *CouponHandler) EXPECT() *CouponHandler_Expecter {
	return &CouponHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type CouponHandler
func (_mock *CouponHandler) Create(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// CouponHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CouponHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *CouponHandler_Expecter) Create(responseWriter interface{}, request interface{}) *CouponHandler_Create_Call {
	return &CouponHandler_Create_Call{Call: _e.mock.On("Create", responseWriter, request)}
}

func (_c *CouponHandler_Create_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *CouponHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponHandler_Create_Call) Return() *CouponHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *CouponHandler_Create_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *CouponHandler_Create_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type CouponHandler
func (_mock *CouponHandler) Delete(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// CouponHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CouponHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *CouponHandler_Expecter) Delete(responseWriter interface{}, request interface{}) *CouponHandler_Delete_Call {
	return &CouponHandler_Delete_Call{Call: _e.mock.On("Delete", responseWriter, request)}
}

func (_c *CouponHandler_Delete_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *CouponHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponHandler_Delete_Call) Return() *CouponHandler_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *CouponHandler_Delete_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *CouponHandler_Delete_Call {
	_c.Run(run)
	return _c
}

// GetAll provides a mock function for the type CouponHandler
func (_mock *CouponHandler) GetAll(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// CouponHandler_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type CouponHandler_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *CouponHandler_Expecter) GetAll(responseWriter interface{}, request interface{}) *CouponHandler_GetAll_Call {
	return &CouponHandler_GetAll_Call{Call: _e.mock.On("GetAll", responseWriter, request)}
}

func (_c *CouponHandler_GetAll_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *CouponHandler_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponHandler_GetAll_Call) Return() *CouponHandler_GetAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *CouponHandler_GetAll_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *CouponHandler_GetAll_Call {
	_c.Run(run)
	return _c
}

// GetByID provides a mock function for the type CouponHandler
func (_mock *CouponHandler) GetByID(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// CouponHandler_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CouponHandler_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *CouponHandler_Expecter) GetByID(responseWriter interface{}, request interface{}) *CouponHandler_GetByID_Call {
	return &CouponHandler_GetByID_Call{Call: _e.mock.On("GetByID", responseWriter, request)}
}

func (_c *CouponHandler_GetByID_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *CouponHandler_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponHandler_GetByID_Call) Return() *CouponHandler_GetByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *CouponHandler_GetByID_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *CouponHandler_GetByID_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function for the type CouponHandler
func (_mock *CouponHandler) Update(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// CouponHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CouponHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *CouponHandler_Expecter) Update(responseWriter interface{}, request interface{}) *CouponHandler_Update_Call {
	return &CouponHandler_Update_Call{Call: _e.mock.On("Update", responseWriter, request)}
}

func (_c *CouponHandler_Update_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *CouponHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponHandler_Update_Call) Return() *CouponHandler_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *CouponHandler_Update_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *CouponHandler_Update_Call {
	_c.Run(run)
	return _c
}
