// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewCreateProductUseCase creates a new instance of CreateProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateProductUseCase {
	mock := &CreateProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CreateProductUseCase is an autogenerated mock type for the CreateProductUseCase type
type CreateProductUseCase struct {
	mock.Mock
}

type CreateProductUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateProductUseCase) EXPECT() *CreateProductUseCase_Expecter {
	return &CreateProductUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type CreateProductUseCase
func (_mock *CreateProductUseCase) Execute(ctx context.Context, product *models.Product, imageBuffers [][]byte, shopID int) (*models.Product, error) {
	ret := _mock.Called(ctx, product, imageBuffers, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Product, [][]byte, int) (*models.Product, error)); ok {
		return returnFunc(ctx, product, imageBuffers, shopID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Product, [][]byte, int) *models.Product); ok {
		r0 = returnFunc(ctx, product, imageBuffers, shopID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Product, [][]byte, int) error); ok {
		r1 = returnFunc(ctx, product, imageBuffers, shopID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CreateProductUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CreateProductUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - product *models.Product
//   - imageBuffers [][]byte
//   - shopID int
func (_e *CreateProductUseCase_Expecter) Execute(ctx interface{}, product interface{}, imageBuffers interface{}, shopID interface{}) *CreateProductUseCase_Execute_Call {
	return &CreateProductUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, product, imageBuffers, shopID)}
}

func (_c *CreateProductUseCase_Execute_Call) Run(run func(ctx context.Context, product *models.Product, imageBuffers [][]byte, shopID int)) *CreateProductUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Product
		if args[1] != nil {
			arg1 = args[1].(*models.Product)
		}
		var arg2 [][]byte
		if args[2] != nil {
			arg2 = args[2].([][]byte)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CreateProductUseCase_Execute_Call) Return(product1 *models.Product, err error) *CreateProductUseCase_Execute_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *CreateProductUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, product *models.Product, imageBuffers [][]byte, shopID int) (*models.Product, error)) *CreateProductUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
