// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewDataBaseConnection creates a new instance of DataBaseConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataBaseConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataBaseConnection {
	mock := &DataBaseConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DataBaseConnection is an autogenerated mock type for the DataBaseConnection type
type DataBaseConnection struct {
	mock.Mock
}

type DataBaseConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *DataBaseConnection) EXPECT() *DataBaseConnection_Expecter {
	return &DataBaseConnection_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type DataBaseConnection
func (_mock *DataBaseConnection) Connect() *sql.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 *sql.DB
	if returnFunc, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}
	return r0
}

// DataBaseConnection_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type DataBaseConnection_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *DataBaseConnection_Expecter) Connect() *DataBaseConnection_Connect_Call {
	return &DataBaseConnection_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *DataBaseConnection_Connect_Call) Run(run func()) *DataBaseConnection_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DataBaseConnection_Connect_Call) Return(dB *sql.DB) *DataBaseConnection_Connect_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *DataBaseConnection_Connect_Call) RunAndReturn(run func() *sql.DB) *DataBaseConnection_Connect_Call {
	_c.Call.Return(run)
	return _c
}
