// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewDeleteProductUseCase creates a new instance of DeleteProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteProductUseCase {
	mock := &DeleteProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DeleteProductUseCase is an autogenerated mock type for the DeleteProductUseCase type
type DeleteProductUseCase struct {
	mock.Mock
}

type DeleteProductUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteProductUseCase) EXPECT() *DeleteProductUseCase_Expecter {
	return &DeleteProductUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type DeleteProductUseCase
func (_mock *DeleteProductUseCase) Execute(ctx context.Context, productID int, shopID int) error {
	ret := _mock.Called(ctx, productID, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, productID, shopID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DeleteProductUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteProductUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - productID int
//   - shopID int
func (_e *DeleteProductUseCase_Expecter) Execute(ctx interface{}, productID interface{}, shopID interface{}) *DeleteProductUseCase_Execute_Call {
	return &DeleteProductUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, productID, shopID)}
}

func (_c *DeleteProductUseCase_Execute_Call) Run(run func(ctx context.Context, productID int, shopID int)) *DeleteProductUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DeleteProductUseCase_Execute_Call) Return(err error) *DeleteProductUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DeleteProductUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, productID int, shopID int) error) *DeleteProductUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
