// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewDeleteStaffUseCase creates a new instance of DeleteStaffUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteStaffUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteStaffUseCase {
	mock := &DeleteStaffUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DeleteStaffUseCase is an autogenerated mock type for the DeleteStaffUseCase type
type DeleteStaffUseCase struct {
	mock.Mock
}

type DeleteStaffUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteStaffUseCase) EXPECT() *DeleteStaffUseCase_Expecter {
	return &DeleteStaffUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type DeleteStaffUseCase
func (_mock *DeleteStaffUseCase) Execute(ctx context.Context, staffID int, shopID int) error {
	ret := _mock.Called(ctx, staffID, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, staffID, shopID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DeleteStaffUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteStaffUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int
//   - shopID int
func (_e *DeleteStaffUseCase_Expecter) Execute(ctx interface{}, staffID interface{}, shopID interface{}) *DeleteStaffUseCase_Execute_Call {
	return &DeleteStaffUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, staffID, shopID)}
}

func (_c *DeleteStaffUseCase_Execute_Call) Run(run func(ctx context.Context, staffID int, shopID int)) *DeleteStaffUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DeleteStaffUseCase_Execute_Call) Return(err error) *DeleteStaffUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DeleteStaffUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, staffID int, shopID int) error) *DeleteStaffUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
