// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewDeliveryMethodRepository creates a new instance of DeliveryMethodRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeliveryMethodRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeliveryMethodRepository {
	mock := &DeliveryMethodRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DeliveryMethodRepository is an autogenerated mock type for the DeliveryMethodRepository type
type DeliveryMethodRepository struct {
	mock.Mock
}

type DeliveryMethodRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DeliveryMethodRepository) EXPECT() *DeliveryMethodRepository_Expecter {
	return &DeliveryMethodRepository_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type DeliveryMethodRepository
func (_mock *DeliveryMethodRepository) GetAll(ctx context.Context) ([]*models.DeliveryMethod, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.DeliveryMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.DeliveryMethod, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.DeliveryMethod); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.DeliveryMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DeliveryMethodRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type DeliveryMethodRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DeliveryMethodRepository_Expecter) GetAll(ctx interface{}) *DeliveryMethodRepository_GetAll_Call {
	return &DeliveryMethodRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *DeliveryMethodRepository_GetAll_Call) Run(run func(ctx context.Context)) *DeliveryMethodRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DeliveryMethodRepository_GetAll_Call) Return(deliveryMethods []*models.DeliveryMethod, err error) *DeliveryMethodRepository_GetAll_Call {
	_c.Call.Return(deliveryMethods, err)
	return _c
}

func (_c *DeliveryMethodRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]*models.DeliveryMethod, error)) *DeliveryMethodRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function for the type DeliveryMethodRepository
func (_mock *DeliveryMethodRepository) GetByCode(ctx context.Context, code models.DeliveryMethodCode) (*models.DeliveryMethod, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *models.DeliveryMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DeliveryMethodCode) (*models.DeliveryMethod, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DeliveryMethodCode) *models.DeliveryMethod); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DeliveryMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.DeliveryMethodCode) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DeliveryMethodRepository_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type DeliveryMethodRepository_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code models.DeliveryMethodCode
func (_e *DeliveryMethodRepository_Expecter) GetByCode(ctx interface{}, code interface{}) *DeliveryMethodRepository_GetByCode_Call {
	return &DeliveryMethodRepository_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *DeliveryMethodRepository_GetByCode_Call) Run(run func(ctx context.Context, code models.DeliveryMethodCode)) *DeliveryMethodRepository_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.DeliveryMethodCode
		if args[1] != nil {
			arg1 = args[1].(models.DeliveryMethodCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DeliveryMethodRepository_GetByCode_Call) Return(deliveryMethod *models.DeliveryMethod, err error) *DeliveryMethodRepository_GetByCode_Call {
	_c.Call.Return(deliveryMethod, err)
	return _c
}

func (_c *DeliveryMethodRepository_GetByCode_Call) RunAndReturn(run func(ctx context.Context, code models.DeliveryMethodCode) (*models.DeliveryMethod, error)) *DeliveryMethodRepository_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type DeliveryMethodRepository
func (_mock *DeliveryMethodRepository) GetByID(ctx context.Context, id int) (*models.DeliveryMethod, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.DeliveryMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.DeliveryMethod, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.DeliveryMethod); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DeliveryMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DeliveryMethodRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type DeliveryMethodRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *DeliveryMethodRepository_Expecter) GetByID(ctx interface{}, id interface{}) *DeliveryMethodRepository_GetByID_Call {
	return &DeliveryMethodRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *DeliveryMethodRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *DeliveryMethodRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DeliveryMethodRepository_GetByID_Call) Return(deliveryMethod *models.DeliveryMethod, err error) *DeliveryMethodRepository_GetByID_Call {
	_c.Call.Return(deliveryMethod, err)
	return _c
}

func (_c *DeliveryMethodRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.DeliveryMethod, error)) *DeliveryMethodRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
