// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewGetAllCategoriesByShopIDWithFiltersUseCase creates a new instance of GetAllCategoriesByShopIDWithFiltersUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetAllCategoriesByShopIDWithFiltersUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetAllCategoriesByShopIDWithFiltersUseCase {
	mock := &GetAllCategoriesByShopIDWithFiltersUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GetAllCategoriesByShopIDWithFiltersUseCase is an autogenerated mock type for the GetAllCategoriesByShopIDWithFiltersUseCase type
type GetAllCategoriesByShopIDWithFiltersUseCase struct {
	mock.Mock
}

type GetAllCategoriesByShopIDWithFiltersUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetAllCategoriesByShopIDWithFiltersUseCase) EXPECT() *GetAllCategoriesByShopIDWithFiltersUseCase_Expecter {
	return &GetAllCategoriesByShopIDWithFiltersUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type GetAllCategoriesByShopIDWithFiltersUseCase
func (_mock *GetAllCategoriesByShopIDWithFiltersUseCase) Execute(ctx context.Context, shopID int, filters models.CategoryFilters) ([]*models.Category, string, bool, *int, error) {
	ret := _mock.Called(ctx, shopID, filters)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*models.Category
	var r1 string
	var r2 bool
	var r3 *int
	var r4 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.CategoryFilters) ([]*models.Category, string, bool, *int, error)); ok {
		return returnFunc(ctx, shopID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.CategoryFilters) []*models.Category); ok {
		r0 = returnFunc(ctx, shopID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.CategoryFilters) string); ok {
		r1 = returnFunc(ctx, shopID, filters)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, models.CategoryFilters) bool); ok {
		r2 = returnFunc(ctx, shopID, filters)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, int, models.CategoryFilters) *int); ok {
		r3 = returnFunc(ctx, shopID, filters)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).(*int)
		}
	}
	if returnFunc, ok := ret.Get(4).(func(context.Context, int, models.CategoryFilters) error); ok {
		r4 = returnFunc(ctx, shopID, filters)
	} else {
		r4 = ret.Error(4)
	}
	return r0, r1, r2, r3, r4
}

// GetAllCategoriesByShopIDWithFiltersUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetAllCategoriesByShopIDWithFiltersUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - filters models.CategoryFilters
func (_e *GetAllCategoriesByShopIDWithFiltersUseCase_Expecter) Execute(ctx interface{}, shopID interface{}, filters interface{}) *GetAllCategoriesByShopIDWithFiltersUseCase_Execute_Call {
	return &GetAllCategoriesByShopIDWithFiltersUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, shopID, filters)}
}

func (_c *GetAllCategoriesByShopIDWithFiltersUseCase_Execute_Call) Run(run func(ctx context.Context, shopID int, filters models.CategoryFilters)) *GetAllCategoriesByShopIDWithFiltersUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.CategoryFilters
		if args[2] != nil {
			arg2 = args[2].(models.CategoryFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GetAllCategoriesByShopIDWithFiltersUseCase_Execute_Call) Return(categorys []*models.Category, s string, b bool, n *int, err error) *GetAllCategoriesByShopIDWithFiltersUseCase_Execute_Call {
	_c.Call.Return(categorys, s, b, n, err)
	return _c
}

func (_c *GetAllCategoriesByShopIDWithFiltersUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, shopID int, filters models.CategoryFilters) ([]*models.Category, string, bool, *int, error)) *GetAllCategoriesByShopIDWithFiltersUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
