// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewGetAllStaffByShopIDUseCase creates a new instance of GetAllStaffByShopIDUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetAllStaffByShopIDUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetAllStaffByShopIDUseCase {
	mock := &GetAllStaffByShopIDUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GetAllStaffByShopIDUseCase is an autogenerated mock type for the GetAllStaffByShopIDUseCase type
type GetAllStaffByShopIDUseCase struct {
	mock.Mock
}

type GetAllStaffByShopIDUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetAllStaffByShopIDUseCase) EXPECT() *GetAllStaffByShopIDUseCase_Expecter {
	return &GetAllStaffByShopIDUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type GetAllStaffByShopIDUseCase
func (_mock *GetAllStaffByShopIDUseCase) Execute(ctx context.Context, shopID int, filters models.StaffFilters) ([]*models.Staff, string, bool, *int, error) {
	ret := _mock.Called(ctx, shopID, filters)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*models.Staff
	var r1 string
	var r2 bool
	var r3 *int
	var r4 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.StaffFilters) ([]*models.Staff, string, bool, *int, error)); ok {
		return returnFunc(ctx, shopID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.StaffFilters) []*models.Staff); ok {
		r0 = returnFunc(ctx, shopID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Staff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.StaffFilters) string); ok {
		r1 = returnFunc(ctx, shopID, filters)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, models.StaffFilters) bool); ok {
		r2 = returnFunc(ctx, shopID, filters)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, int, models.StaffFilters) *int); ok {
		r3 = returnFunc(ctx, shopID, filters)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).(*int)
		}
	}
	if returnFunc, ok := ret.Get(4).(func(context.Context, int, models.StaffFilters) error); ok {
		r4 = returnFunc(ctx, shopID, filters)
	} else {
		r4 = ret.Error(4)
	}
	return r0, r1, r2, r3, r4
}

// GetAllStaffByShopIDUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetAllStaffByShopIDUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - filters models.StaffFilters
func (_e *GetAllStaffByShopIDUseCase_Expecter) Execute(ctx interface{}, shopID interface{}, filters interface{}) *GetAllStaffByShopIDUseCase_Execute_Call {
	return &GetAllStaffByShopIDUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, shopID, filters)}
}

func (_c *GetAllStaffByShopIDUseCase_Execute_Call) Run(run func(ctx context.Context, shopID int, filters models.StaffFilters)) *GetAllStaffByShopIDUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.StaffFilters
		if args[2] != nil {
			arg2 = args[2].(models.StaffFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GetAllStaffByShopIDUseCase_Execute_Call) Return(staffs []*models.Staff, s string, b bool, n *int, err error) *GetAllStaffByShopIDUseCase_Execute_Call {
	_c.Call.Return(staffs, s, b, n, err)
	return _c
}

func (_c *GetAllStaffByShopIDUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, shopID int, filters models.StaffFilters) ([]*models.Staff, string, bool, *int, error)) *GetAllStaffByShopIDUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
