// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewGetOrderByIDUseCase creates a new instance of GetOrderByIDUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetOrderByIDUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetOrderByIDUseCase {
	mock := &GetOrderByIDUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GetOrderByIDUseCase is an autogenerated mock type for the GetOrderByIDUseCase type
type GetOrderByIDUseCase struct {
	mock.Mock
}

type GetOrderByIDUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetOrderByIDUseCase) EXPECT() *GetOrderByIDUseCase_Expecter {
	return &GetOrderByIDUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type GetOrderByIDUseCase
func (_mock *GetOrderByIDUseCase) Execute(ctx context.Context, shopID int, orderID int) (*models.Order, error) {
	ret := _mock.Called(ctx, shopID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*models.Order, error)); ok {
		return returnFunc(ctx, shopID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *models.Order); ok {
		r0 = returnFunc(ctx, shopID, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, shopID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetOrderByIDUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetOrderByIDUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - orderID int
func (_e *GetOrderByIDUseCase_Expecter) Execute(ctx interface{}, shopID interface{}, orderID interface{}) *GetOrderByIDUseCase_Execute_Call {
	return &GetOrderByIDUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, shopID, orderID)}
}

func (_c *GetOrderByIDUseCase_Execute_Call) Run(run func(ctx context.Context, shopID int, orderID int)) *GetOrderByIDUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GetOrderByIDUseCase_Execute_Call) Return(order *models.Order, err error) *GetOrderByIDUseCase_Execute_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *GetOrderByIDUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, shopID int, orderID int) (*models.Order, error)) *GetOrderByIDUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
