// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewGetShopByIDUseCase creates a new instance of GetShopByIDUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetShopByIDUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetShopByIDUseCase {
	mock := &GetShopByIDUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GetShopByIDUseCase is an autogenerated mock type for the GetShopByIDUseCase type
type GetShopByIDUseCase struct {
	mock.Mock
}

type GetShopByIDUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetShopByIDUseCase) EXPECT() *GetShopByIDUseCase_Expecter {
	return &GetShopByIDUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type GetShopByIDUseCase
func (_mock *GetShopByIDUseCase) Execute(ctx context.Context, shopID int) (*models.Shop, error) {
	ret := _mock.Called(ctx, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *models.Shop
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Shop, error)); ok {
		return returnFunc(ctx, shopID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Shop); ok {
		r0 = returnFunc(ctx, shopID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Shop)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, shopID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetShopByIDUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetShopByIDUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
func (_e *GetShopByIDUseCase_Expecter) Execute(ctx interface{}, shopID interface{}) *GetShopByIDUseCase_Execute_Call {
	return &GetShopByIDUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, shopID)}
}

func (_c *GetShopByIDUseCase_Execute_Call) Run(run func(ctx context.Context, shopID int)) *GetShopByIDUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GetShopByIDUseCase_Execute_Call) Return(shop *models.Shop, err error) *GetShopByIDUseCase_Execute_Call {
	_c.Call.Return(shop, err)
	return _c
}

func (_c *GetShopByIDUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, shopID int) (*models.Shop, error)) *GetShopByIDUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
