// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewGetStoreFeaturedProductsUseCase creates a new instance of GetStoreFeaturedProductsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetStoreFeaturedProductsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetStoreFeaturedProductsUseCase {
	mock := &GetStoreFeaturedProductsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GetStoreFeaturedProductsUseCase is an autogenerated mock type for the GetStoreFeaturedProductsUseCase type
type GetStoreFeaturedProductsUseCase struct {
	mock.Mock
}

type GetStoreFeaturedProductsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetStoreFeaturedProductsUseCase) EXPECT() *GetStoreFeaturedProductsUseCase_Expecter {
	return &GetStoreFeaturedProductsUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type GetStoreFeaturedProductsUseCase
func (_mock *GetStoreFeaturedProductsUseCase) Execute(ctx context.Context, slug string, filters models.ProductFilters) ([]*models.Product, string, bool, error) {
	ret := _mock.Called(ctx, slug, filters)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*models.Product
	var r1 string
	var r2 bool
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ProductFilters) ([]*models.Product, string, bool, error)); ok {
		return returnFunc(ctx, slug, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ProductFilters) []*models.Product); ok {
		r0 = returnFunc(ctx, slug, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.ProductFilters) string); ok {
		r1 = returnFunc(ctx, slug, filters)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, models.ProductFilters) bool); ok {
		r2 = returnFunc(ctx, slug, filters)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, models.ProductFilters) error); ok {
		r3 = returnFunc(ctx, slug, filters)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// GetStoreFeaturedProductsUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetStoreFeaturedProductsUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - filters models.ProductFilters
func (_e *GetStoreFeaturedProductsUseCase_Expecter) Execute(ctx interface{}, slug interface{}, filters interface{}) *GetStoreFeaturedProductsUseCase_Execute_Call {
	return &GetStoreFeaturedProductsUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, slug, filters)}
}

func (_c *GetStoreFeaturedProductsUseCase_Execute_Call) Run(run func(ctx context.Context, slug string, filters models.ProductFilters)) *GetStoreFeaturedProductsUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.ProductFilters
		if args[2] != nil {
			arg2 = args[2].(models.ProductFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GetStoreFeaturedProductsUseCase_Execute_Call) Return(products []*models.Product, s string, b bool, err error) *GetStoreFeaturedProductsUseCase_Execute_Call {
	_c.Call.Return(products, s, b, err)
	return _c
}

func (_c *GetStoreFeaturedProductsUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, slug string, filters models.ProductFilters) ([]*models.Product, string, bool, error)) *GetStoreFeaturedProductsUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
