// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewGetStoreCategoriesUseCase creates a new instance of GetStoreCategoriesUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetStoreCategoriesUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetStoreCategoriesUseCase {
	mock := &GetStoreCategoriesUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GetStoreCategoriesUseCase is an autogenerated mock type for the GetStoreCategoriesUseCase type
type GetStoreCategoriesUseCase struct {
	mock.Mock
}

type GetStoreCategoriesUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetStoreCategoriesUseCase) EXPECT() *GetStoreCategoriesUseCase_Expecter {
	return &GetStoreCategoriesUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type GetStoreCategoriesUseCase
func (_mock *GetStoreCategoriesUseCase) Execute(ctx context.Context, slug string, filters models.CategoryFilters) ([]*models.Category, string, bool, error) {
	ret := _mock.Called(ctx, slug, filters)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*models.Category
	var r1 string
	var r2 bool
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.CategoryFilters) ([]*models.Category, string, bool, error)); ok {
		return returnFunc(ctx, slug, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.CategoryFilters) []*models.Category); ok {
		r0 = returnFunc(ctx, slug, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.CategoryFilters) string); ok {
		r1 = returnFunc(ctx, slug, filters)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, models.CategoryFilters) bool); ok {
		r2 = returnFunc(ctx, slug, filters)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, models.CategoryFilters) error); ok {
		r3 = returnFunc(ctx, slug, filters)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// GetStoreCategoriesUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetStoreCategoriesUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - filters models.CategoryFilters
func (_e *GetStoreCategoriesUseCase_Expecter) Execute(ctx interface{}, slug interface{}, filters interface{}) *GetStoreCategoriesUseCase_Execute_Call {
	return &GetStoreCategoriesUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, slug, filters)}
}

func (_c *GetStoreCategoriesUseCase_Execute_Call) Run(run func(ctx context.Context, slug string, filters models.CategoryFilters)) *GetStoreCategoriesUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.CategoryFilters
		if args[2] != nil {
			arg2 = args[2].(models.CategoryFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GetStoreCategoriesUseCase_Execute_Call) Return(categorys []*models.Category, s string, b bool, err error) *GetStoreCategoriesUseCase_Execute_Call {
	_c.Call.Return(categorys, s, b, err)
	return _c
}

func (_c *GetStoreCategoriesUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, slug string, filters models.CategoryFilters) ([]*models.Category, string, bool, error)) *GetStoreCategoriesUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
