// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewGetStoreBySlugUseCase creates a new instance of GetStoreBySlugUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetStoreBySlugUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetStoreBySlugUseCase {
	mock := &GetStoreBySlugUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GetStoreBySlugUseCase is an autogenerated mock type for the GetStoreBySlugUseCase type
type GetStoreBySlugUseCase struct {
	mock.Mock
}

type GetStoreBySlugUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetStoreBySlugUseCase) EXPECT() *GetStoreBySlugUseCase_Expecter {
	return &GetStoreBySlugUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type GetStoreBySlugUseCase
func (_mock *GetStoreBySlugUseCase) Execute(ctx context.Context, slug string) (*models.Store, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *models.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Store, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Store); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetStoreBySlugUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetStoreBySlugUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *GetStoreBySlugUseCase_Expecter) Execute(ctx interface{}, slug interface{}) *GetStoreBySlugUseCase_Execute_Call {
	return &GetStoreBySlugUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, slug)}
}

func (_c *GetStoreBySlugUseCase_Execute_Call) Run(run func(ctx context.Context, slug string)) *GetStoreBySlugUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GetStoreBySlugUseCase_Execute_Call) Return(store *models.Store, err error) *GetStoreBySlugUseCase_Execute_Call {
	_c.Call.Return(store, err)
	return _c
}

func (_c *GetStoreBySlugUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, slug string) (*models.Store, error)) *GetStoreBySlugUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
