// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewGetTopProductsUseCase creates a new instance of GetTopProductsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetTopProductsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetTopProductsUseCase {
	mock := &GetTopProductsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GetTopProductsUseCase is an autogenerated mock type for the GetTopProductsUseCase type
type GetTopProductsUseCase struct {
	mock.Mock
}

type GetTopProductsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetTopProductsUseCase) EXPECT() *GetTopProductsUseCase_Expecter {
	return &GetTopProductsUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type GetTopProductsUseCase
func (_mock *GetTopProductsUseCase) Execute(ctx context.Context, shopID int, filters models.MetricsFilters) ([]models.TopProduct, error) {
	ret := _mock.Called(ctx, shopID, filters)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []models.TopProduct
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.MetricsFilters) ([]models.TopProduct, error)); ok {
		return returnFunc(ctx, shopID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.MetricsFilters) []models.TopProduct); ok {
		r0 = returnFunc(ctx, shopID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TopProduct)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.MetricsFilters) error); ok {
		r1 = returnFunc(ctx, shopID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetTopProductsUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetTopProductsUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - filters models.MetricsFilters
func (_e *GetTopProductsUseCase_Expecter) Execute(ctx interface{}, shopID interface{}, filters interface{}) *GetTopProductsUseCase_Execute_Call {
	return &GetTopProductsUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, shopID, filters)}
}

func (_c *GetTopProductsUseCase_Execute_Call) Run(run func(ctx context.Context, shopID int, filters models.MetricsFilters)) *GetTopProductsUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.MetricsFilters
		if args[2] != nil {
			arg2 = args[2].(models.MetricsFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GetTopProductsUseCase_Execute_Call) Return(topProducts []models.TopProduct, err error) *GetTopProductsUseCase_Execute_Call {
	_c.Call.Return(topProducts, err)
	return _c
}

func (_c *GetTopProductsUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, shopID int, filters models.MetricsFilters) ([]models.TopProduct, error)) *GetTopProductsUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
