// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewHealthHandler creates a new instance of HealthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthHandler {
	mock := &HealthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HealthHandler is an autogenerated mock type for the HealthHandler type
type HealthHandler struct {
	mock.Mock
}

type HealthHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthHandler) EXPECT() *HealthHandler_Expecter {
	return &HealthHandler_Expecter{mock: &_m.Mock}
}

// Health provides a mock function for the type HealthHandler
func (_mock *HealthHandler) Health(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// HealthHandler_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type HealthHandler_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *HealthHandler_Expecter) Health(w interface{}, r interface{}) *HealthHandler_Health_Call {
	return &HealthHandler_Health_Call{Call: _e.mock.On("Health", w, r)}
}

func (_c *HealthHandler_Health_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *HealthHandler_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HealthHandler_Health_Call) Return() *HealthHandler_Health_Call {
	_c.Call.Return()
	return _c
}

func (_c *HealthHandler_Health_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *HealthHandler_Health_Call {
	_c.Run(run)
	return _c
}
