// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewIdentifiable creates a new instance of Identifiable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentifiable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Identifiable {
	mock := &Identifiable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Identifiable is an autogenerated mock type for the Identifiable type
type Identifiable struct {
	mock.Mock
}

type Identifiable_Expecter struct {
	mock *mock.Mock
}

func (_m *Identifiable) EXPECT() *Identifiable_Expecter {
	return &Identifiable_Expecter{mock: &_m.Mock}
}

// GetID provides a mock function for the type Identifiable
func (_mock *Identifiable) GetID() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// Identifiable_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type Identifiable_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *Identifiable_Expecter) GetID() *Identifiable_GetID_Call {
	return &Identifiable_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *Identifiable_GetID_Call) Run(run func()) *Identifiable_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identifiable_GetID_Call) Return(n int) *Identifiable_GetID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *Identifiable_GetID_Call) RunAndReturn(run func() int) *Identifiable_GetID_Call {
	_c.Call.Return(run)
	return _c
}
