// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMetricsHandler creates a new instance of MetricsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsHandler {
	mock := &MetricsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MetricsHandler is an autogenerated mock type for the MetricsHandler type
type MetricsHandler struct {
	mock.Mock
}

type MetricsHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsHandler) EXPECT() *MetricsHandler_Expecter {
	return &MetricsHandler_Expecter{mock: &_m.Mock}
}

// GetDashboard provides a mock function for the type MetricsHandler
func (_mock *MetricsHandler) GetDashboard(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MetricsHandler_GetDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDashboard'
type MetricsHandler_GetDashboard_Call struct {
	*mock.Call
}

// GetDashboard is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MetricsHandler_Expecter) GetDashboard(responseWriter interface{}, request interface{}) *MetricsHandler_GetDashboard_Call {
	return &MetricsHandler_GetDashboard_Call{Call: _e.mock.On("GetDashboard", responseWriter, request)}
}

func (_c *MetricsHandler_GetDashboard_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MetricsHandler_GetDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetricsHandler_GetDashboard_Call) Return() *MetricsHandler_GetDashboard_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsHandler_GetDashboard_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MetricsHandler_GetDashboard_Call {
	_c.Run(run)
	return _c
}

// GetRevenueTrend provides a mock function for the type MetricsHandler
func (_mock *MetricsHandler) GetRevenueTrend(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MetricsHandler_GetRevenueTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRevenueTrend'
type MetricsHandler_GetRevenueTrend_Call struct {
	*mock.Call
}

// GetRevenueTrend is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MetricsHandler_Expecter) GetRevenueTrend(responseWriter interface{}, request interface{}) *MetricsHandler_GetRevenueTrend_Call {
	return &MetricsHandler_GetRevenueTrend_Call{Call: _e.mock.On("GetRevenueTrend", responseWriter, request)}
}

func (_c *MetricsHandler_GetRevenueTrend_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MetricsHandler_GetRevenueTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetricsHandler_GetRevenueTrend_Call) Return() *MetricsHandler_GetRevenueTrend_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsHandler_GetRevenueTrend_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MetricsHandler_GetRevenueTrend_Call {
	_c.Run(run)
	return _c
}

// GetTopCustomers provides a mock function for the type MetricsHandler
func (_mock *MetricsHandler) GetTopCustomers(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MetricsHandler_GetTopCustomers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopCustomers'
type MetricsHandler_GetTopCustomers_Call struct {
	*mock.Call
}

// GetTopCustomers is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MetricsHandler_Expecter) GetTopCustomers(responseWriter interface{}, request interface{}) *MetricsHandler_GetTopCustomers_Call {
	return &MetricsHandler_GetTopCustomers_Call{Call: _e.mock.On("GetTopCustomers", responseWriter, request)}
}

func (_c *MetricsHandler_GetTopCustomers_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MetricsHandler_GetTopCustomers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetricsHandler_GetTopCustomers_Call) Return() *MetricsHandler_GetTopCustomers_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsHandler_GetTopCustomers_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MetricsHandler_GetTopCustomers_Call {
	_c.Run(run)
	return _c
}

// GetTopProducts provides a mock function for the type MetricsHandler
func (_mock *MetricsHandler) GetTopProducts(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MetricsHandler_GetTopProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopProducts'
type MetricsHandler_GetTopProducts_Call struct {
	*mock.Call
}

// GetTopProducts is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MetricsHandler_Expecter) GetTopProducts(responseWriter interface{}, request interface{}) *MetricsHandler_GetTopProducts_Call {
	return &MetricsHandler_GetTopProducts_Call{Call: _e.mock.On("GetTopProducts", responseWriter, request)}
}

func (_c *MetricsHandler_GetTopProducts_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MetricsHandler_GetTopProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetricsHandler_GetTopProducts_Call) Return() *MetricsHandler_GetTopProducts_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsHandler_GetTopProducts_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MetricsHandler_GetTopProducts_Call {
	_c.Run(run)
	return _c
}
