// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMetricsRepository creates a new instance of MetricsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsRepository {
	mock := &MetricsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MetricsRepository is an autogenerated mock type for the MetricsRepository type
type MetricsRepository struct {
	mock.Mock
}

type MetricsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsRepository) EXPECT() *MetricsRepository_Expecter {
	return &MetricsRepository_Expecter{mock: &_m.Mock}
}

// GetAvgCompletionTime provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetAvgCompletionTime(ctx context.Context, shopID int, from time.Time, to time.Time) (*float64, error) {
	ret := _mock.Called(ctx, shopID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetAvgCompletionTime")
	}

	var r0 *float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) (*float64, error)); ok {
		return returnFunc(ctx, shopID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) *float64); ok {
		r0 = returnFunc(ctx, shopID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, shopID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetAvgCompletionTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvgCompletionTime'
type MetricsRepository_GetAvgCompletionTime_Call struct {
	*mock.Call
}

// GetAvgCompletionTime is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
func (_e *MetricsRepository_Expecter) GetAvgCompletionTime(ctx interface{}, shopID interface{}, from interface{}, to interface{}) *MetricsRepository_GetAvgCompletionTime_Call {
	return &MetricsRepository_GetAvgCompletionTime_Call{Call: _e.mock.On("GetAvgCompletionTime", ctx, shopID, from, to)}
}

func (_c *MetricsRepository_GetAvgCompletionTime_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time)) *MetricsRepository_GetAvgCompletionTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetAvgCompletionTime_Call) Return(f *float64, err error) *MetricsRepository_GetAvgCompletionTime_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MetricsRepository_GetAvgCompletionTime_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time) (*float64, error)) *MetricsRepository_GetAvgCompletionTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerOverview provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetCustomerOverview(ctx context.Context, shopID int, from time.Time, to time.Time) (models.CustomerOverview, error) {
	ret := _mock.Called(ctx, shopID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerOverview")
	}

	var r0 models.CustomerOverview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) (models.CustomerOverview, error)); ok {
		return returnFunc(ctx, shopID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) models.CustomerOverview); ok {
		r0 = returnFunc(ctx, shopID, from, to)
	} else {
		r0 = ret.Get(0).(models.CustomerOverview)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, shopID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetCustomerOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerOverview'
type MetricsRepository_GetCustomerOverview_Call struct {
	*mock.Call
}

// GetCustomerOverview is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
func (_e *MetricsRepository_Expecter) GetCustomerOverview(ctx interface{}, shopID interface{}, from interface{}, to interface{}) *MetricsRepository_GetCustomerOverview_Call {
	return &MetricsRepository_GetCustomerOverview_Call{Call: _e.mock.On("GetCustomerOverview", ctx, shopID, from, to)}
}

func (_c *MetricsRepository_GetCustomerOverview_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time)) *MetricsRepository_GetCustomerOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetCustomerOverview_Call) Return(customerOverview models.CustomerOverview, err error) *MetricsRepository_GetCustomerOverview_Call {
	_c.Call.Return(customerOverview, err)
	return _c
}

func (_c *MetricsRepository_GetCustomerOverview_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time) (models.CustomerOverview, error)) *MetricsRepository_GetCustomerOverview_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeliveryMethodDistribution provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetDeliveryMethodDistribution(ctx context.Context, shopID int, from time.Time, to time.Time) ([]models.MethodDistribution, error) {
	ret := _mock.Called(ctx, shopID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetDeliveryMethodDistribution")
	}

	var r0 []models.MethodDistribution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) ([]models.MethodDistribution, error)); ok {
		return returnFunc(ctx, shopID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) []models.MethodDistribution); ok {
		r0 = returnFunc(ctx, shopID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MethodDistribution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, shopID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetDeliveryMethodDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeliveryMethodDistribution'
type MetricsRepository_GetDeliveryMethodDistribution_Call struct {
	*mock.Call
}

// GetDeliveryMethodDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
func (_e *MetricsRepository_Expecter) GetDeliveryMethodDistribution(ctx interface{}, shopID interface{}, from interface{}, to interface{}) *MetricsRepository_GetDeliveryMethodDistribution_Call {
	return &MetricsRepository_GetDeliveryMethodDistribution_Call{Call: _e.mock.On("GetDeliveryMethodDistribution", ctx, shopID, from, to)}
}

func (_c *MetricsRepository_GetDeliveryMethodDistribution_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time)) *MetricsRepository_GetDeliveryMethodDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetDeliveryMethodDistribution_Call) Return(methodDistributions []models.MethodDistribution, err error) *MetricsRepository_GetDeliveryMethodDistribution_Call {
	_c.Call.Return(methodDistributions, err)
	return _c
}

func (_c *MetricsRepository_GetDeliveryMethodDistribution_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time) ([]models.MethodDistribution, error)) *MetricsRepository_GetDeliveryMethodDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderStatusDistribution provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetOrderStatusDistribution(ctx context.Context, shopID int, from time.Time, to time.Time) ([]models.OrderStatusDistribution, error) {
	ret := _mock.Called(ctx, shopID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderStatusDistribution")
	}

	var r0 []models.OrderStatusDistribution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) ([]models.OrderStatusDistribution, error)); ok {
		return returnFunc(ctx, shopID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) []models.OrderStatusDistribution); ok {
		r0 = returnFunc(ctx, shopID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderStatusDistribution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, shopID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetOrderStatusDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderStatusDistribution'
type MetricsRepository_GetOrderStatusDistribution_Call struct {
	*mock.Call
}

// GetOrderStatusDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
func (_e *MetricsRepository_Expecter) GetOrderStatusDistribution(ctx interface{}, shopID interface{}, from interface{}, to interface{}) *MetricsRepository_GetOrderStatusDistribution_Call {
	return &MetricsRepository_GetOrderStatusDistribution_Call{Call: _e.mock.On("GetOrderStatusDistribution", ctx, shopID, from, to)}
}

func (_c *MetricsRepository_GetOrderStatusDistribution_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time)) *MetricsRepository_GetOrderStatusDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetOrderStatusDistribution_Call) Return(orderStatusDistributions []models.OrderStatusDistribution, err error) *MetricsRepository_GetOrderStatusDistribution_Call {
	_c.Call.Return(orderStatusDistributions, err)
	return _c
}

func (_c *MetricsRepository_GetOrderStatusDistribution_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time) ([]models.OrderStatusDistribution, error)) *MetricsRepository_GetOrderStatusDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentMethodDistribution provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetPaymentMethodDistribution(ctx context.Context, shopID int, from time.Time, to time.Time) ([]models.MethodDistribution, error) {
	ret := _mock.Called(ctx, shopID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentMethodDistribution")
	}

	var r0 []models.MethodDistribution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) ([]models.MethodDistribution, error)); ok {
		return returnFunc(ctx, shopID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) []models.MethodDistribution); ok {
		r0 = returnFunc(ctx, shopID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MethodDistribution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, shopID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetPaymentMethodDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentMethodDistribution'
type MetricsRepository_GetPaymentMethodDistribution_Call struct {
	*mock.Call
}

// GetPaymentMethodDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
func (_e *MetricsRepository_Expecter) GetPaymentMethodDistribution(ctx interface{}, shopID interface{}, from interface{}, to interface{}) *MetricsRepository_GetPaymentMethodDistribution_Call {
	return &MetricsRepository_GetPaymentMethodDistribution_Call{Call: _e.mock.On("GetPaymentMethodDistribution", ctx, shopID, from, to)}
}

func (_c *MetricsRepository_GetPaymentMethodDistribution_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time)) *MetricsRepository_GetPaymentMethodDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetPaymentMethodDistribution_Call) Return(methodDistributions []models.MethodDistribution, err error) *MetricsRepository_GetPaymentMethodDistribution_Call {
	_c.Call.Return(methodDistributions, err)
	return _c
}

func (_c *MetricsRepository_GetPaymentMethodDistribution_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time) ([]models.MethodDistribution, error)) *MetricsRepository_GetPaymentMethodDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// GetRevenueSummary provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetRevenueSummary(ctx context.Context, shopID int, from time.Time, to time.Time) (models.RevenueSummary, error) {
	ret := _mock.Called(ctx, shopID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetRevenueSummary")
	}

	var r0 models.RevenueSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) (models.RevenueSummary, error)); ok {
		return returnFunc(ctx, shopID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) models.RevenueSummary); ok {
		r0 = returnFunc(ctx, shopID, from, to)
	} else {
		r0 = ret.Get(0).(models.RevenueSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, shopID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetRevenueSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRevenueSummary'
type MetricsRepository_GetRevenueSummary_Call struct {
	*mock.Call
}

// GetRevenueSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
func (_e *MetricsRepository_Expecter) GetRevenueSummary(ctx interface{}, shopID interface{}, from interface{}, to interface{}) *MetricsRepository_GetRevenueSummary_Call {
	return &MetricsRepository_GetRevenueSummary_Call{Call: _e.mock.On("GetRevenueSummary", ctx, shopID, from, to)}
}

func (_c *MetricsRepository_GetRevenueSummary_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time)) *MetricsRepository_GetRevenueSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetRevenueSummary_Call) Return(revenueSummary models.RevenueSummary, err error) *MetricsRepository_GetRevenueSummary_Call {
	_c.Call.Return(revenueSummary, err)
	return _c
}

func (_c *MetricsRepository_GetRevenueSummary_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time) (models.RevenueSummary, error)) *MetricsRepository_GetRevenueSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetRevenueSummaryBatch provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetRevenueSummaryBatch(ctx context.Context, shopID int, periods []models.RevenuePeriod) ([]models.RevenueSummary, error) {
	ret := _mock.Called(ctx, shopID, periods)

	if len(ret) == 0 {
		panic("no return value specified for GetRevenueSummaryBatch")
	}

	var r0 []models.RevenueSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []models.RevenuePeriod) ([]models.RevenueSummary, error)); ok {
		return returnFunc(ctx, shopID, periods)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []models.RevenuePeriod) []models.RevenueSummary); ok {
		r0 = returnFunc(ctx, shopID, periods)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RevenueSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, []models.RevenuePeriod) error); ok {
		r1 = returnFunc(ctx, shopID, periods)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetRevenueSummaryBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRevenueSummaryBatch'
type MetricsRepository_GetRevenueSummaryBatch_Call struct {
	*mock.Call
}

// GetRevenueSummaryBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - periods []models.RevenuePeriod
func (_e *MetricsRepository_Expecter) GetRevenueSummaryBatch(ctx interface{}, shopID interface{}, periods interface{}) *MetricsRepository_GetRevenueSummaryBatch_Call {
	return &MetricsRepository_GetRevenueSummaryBatch_Call{Call: _e.mock.On("GetRevenueSummaryBatch", ctx, shopID, periods)}
}

func (_c *MetricsRepository_GetRevenueSummaryBatch_Call) Run(run func(ctx context.Context, shopID int, periods []models.RevenuePeriod)) *MetricsRepository_GetRevenueSummaryBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []models.RevenuePeriod
		if args[2] != nil {
			arg2 = args[2].([]models.RevenuePeriod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetRevenueSummaryBatch_Call) Return(revenueSummarys []models.RevenueSummary, err error) *MetricsRepository_GetRevenueSummaryBatch_Call {
	_c.Call.Return(revenueSummarys, err)
	return _c
}

func (_c *MetricsRepository_GetRevenueSummaryBatch_Call) RunAndReturn(run func(ctx context.Context, shopID int, periods []models.RevenuePeriod) ([]models.RevenueSummary, error)) *MetricsRepository_GetRevenueSummaryBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetRevenueTrend provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetRevenueTrend(ctx context.Context, shopID int, from time.Time, to time.Time, tz string) ([]models.RevenueTrendPoint, error) {
	ret := _mock.Called(ctx, shopID, from, to, tz)

	if len(ret) == 0 {
		panic("no return value specified for GetRevenueTrend")
	}

	var r0 []models.RevenueTrendPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time, string) ([]models.RevenueTrendPoint, error)); ok {
		return returnFunc(ctx, shopID, from, to, tz)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time, string) []models.RevenueTrendPoint); ok {
		r0 = returnFunc(ctx, shopID, from, to, tz)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RevenueTrendPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time, string) error); ok {
		r1 = returnFunc(ctx, shopID, from, to, tz)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetRevenueTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRevenueTrend'
type MetricsRepository_GetRevenueTrend_Call struct {
	*mock.Call
}

// GetRevenueTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
//   - tz string
func (_e *MetricsRepository_Expecter) GetRevenueTrend(ctx interface{}, shopID interface{}, from interface{}, to interface{}, tz interface{}) *MetricsRepository_GetRevenueTrend_Call {
	return &MetricsRepository_GetRevenueTrend_Call{Call: _e.mock.On("GetRevenueTrend", ctx, shopID, from, to, tz)}
}

func (_c *MetricsRepository_GetRevenueTrend_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time, tz string)) *MetricsRepository_GetRevenueTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetRevenueTrend_Call) Return(revenueTrendPoints []models.RevenueTrendPoint, err error) *MetricsRepository_GetRevenueTrend_Call {
	_c.Call.Return(revenueTrendPoints, err)
	return _c
}

func (_c *MetricsRepository_GetRevenueTrend_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time, tz string) ([]models.RevenueTrendPoint, error)) *MetricsRepository_GetRevenueTrend_Call {
	_c.Call.Return(run)
	return _c
}

// GetShippingSummary provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetShippingSummary(ctx context.Context, shopID int, from time.Time, to time.Time) (models.ShippingSummary, error) {
	ret := _mock.Called(ctx, shopID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetShippingSummary")
	}

	var r0 models.ShippingSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) (models.ShippingSummary, error)); ok {
		return returnFunc(ctx, shopID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) models.ShippingSummary); ok {
		r0 = returnFunc(ctx, shopID, from, to)
	} else {
		r0 = ret.Get(0).(models.ShippingSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, shopID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetShippingSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShippingSummary'
type MetricsRepository_GetShippingSummary_Call struct {
	*mock.Call
}

// GetShippingSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
func (_e *MetricsRepository_Expecter) GetShippingSummary(ctx interface{}, shopID interface{}, from interface{}, to interface{}) *MetricsRepository_GetShippingSummary_Call {
	return &MetricsRepository_GetShippingSummary_Call{Call: _e.mock.On("GetShippingSummary", ctx, shopID, from, to)}
}

func (_c *MetricsRepository_GetShippingSummary_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time)) *MetricsRepository_GetShippingSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetShippingSummary_Call) Return(shippingSummary models.ShippingSummary, err error) *MetricsRepository_GetShippingSummary_Call {
	_c.Call.Return(shippingSummary, err)
	return _c
}

func (_c *MetricsRepository_GetShippingSummary_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time) (models.ShippingSummary, error)) *MetricsRepository_GetShippingSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopCustomers provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetTopCustomers(ctx context.Context, shopID int, from time.Time, to time.Time, limit int) ([]models.TopCustomer, error) {
	ret := _mock.Called(ctx, shopID, from, to, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopCustomers")
	}

	var r0 []models.TopCustomer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time, int) ([]models.TopCustomer, error)); ok {
		return returnFunc(ctx, shopID, from, to, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time, int) []models.TopCustomer); ok {
		r0 = returnFunc(ctx, shopID, from, to, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TopCustomer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time, int) error); ok {
		r1 = returnFunc(ctx, shopID, from, to, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetTopCustomers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopCustomers'
type MetricsRepository_GetTopCustomers_Call struct {
	*mock.Call
}

// GetTopCustomers is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
//   - limit int
func (_e *MetricsRepository_Expecter) GetTopCustomers(ctx interface{}, shopID interface{}, from interface{}, to interface{}, limit interface{}) *MetricsRepository_GetTopCustomers_Call {
	return &MetricsRepository_GetTopCustomers_Call{Call: _e.mock.On("GetTopCustomers", ctx, shopID, from, to, limit)}
}

func (_c *MetricsRepository_GetTopCustomers_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time, limit int)) *MetricsRepository_GetTopCustomers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetTopCustomers_Call) Return(topCustomers []models.TopCustomer, err error) *MetricsRepository_GetTopCustomers_Call {
	_c.Call.Return(topCustomers, err)
	return _c
}

func (_c *MetricsRepository_GetTopCustomers_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time, limit int) ([]models.TopCustomer, error)) *MetricsRepository_GetTopCustomers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopProducts provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetTopProducts(ctx context.Context, shopID int, from time.Time, to time.Time, sortBy string, limit int) ([]models.TopProduct, error) {
	ret := _mock.Called(ctx, shopID, from, to, sortBy, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopProducts")
	}

	var r0 []models.TopProduct
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time, string, int) ([]models.TopProduct, error)); ok {
		return returnFunc(ctx, shopID, from, to, sortBy, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time, string, int) []models.TopProduct); ok {
		r0 = returnFunc(ctx, shopID, from, to, sortBy, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TopProduct)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time, string, int) error); ok {
		r1 = returnFunc(ctx, shopID, from, to, sortBy, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetTopProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopProducts'
type MetricsRepository_GetTopProducts_Call struct {
	*mock.Call
}

// GetTopProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
//   - sortBy string
//   - limit int
func (_e *MetricsRepository_Expecter) GetTopProducts(ctx interface{}, shopID interface{}, from interface{}, to interface{}, sortBy interface{}, limit interface{}) *MetricsRepository_GetTopProducts_Call {
	return &MetricsRepository_GetTopProducts_Call{Call: _e.mock.On("GetTopProducts", ctx, shopID, from, to, sortBy, limit)}
}

func (_c *MetricsRepository_GetTopProducts_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time, sortBy string, limit int)) *MetricsRepository_GetTopProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetTopProducts_Call) Return(topProducts []models.TopProduct, err error) *MetricsRepository_GetTopProducts_Call {
	_c.Call.Return(topProducts, err)
	return _c
}

func (_c *MetricsRepository_GetTopProducts_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time, sortBy string, limit int) ([]models.TopProduct, error)) *MetricsRepository_GetTopProducts_Call {
	_c.Call.Return(run)
	return _c
}

// GetVisitsSummaryBatch provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetVisitsSummaryBatch(ctx context.Context, shopID int, periods []models.RevenuePeriod) ([]int, error) {
	ret := _mock.Called(ctx, shopID, periods)

	if len(ret) == 0 {
		panic("no return value specified for GetVisitsSummaryBatch")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []models.RevenuePeriod) ([]int, error)); ok {
		return returnFunc(ctx, shopID, periods)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []models.RevenuePeriod) []int); ok {
		r0 = returnFunc(ctx, shopID, periods)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, []models.RevenuePeriod) error); ok {
		r1 = returnFunc(ctx, shopID, periods)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetVisitsSummaryBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVisitsSummaryBatch'
type MetricsRepository_GetVisitsSummaryBatch_Call struct {
	*mock.Call
}

// GetVisitsSummaryBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - periods []models.RevenuePeriod
func (_e *MetricsRepository_Expecter) GetVisitsSummaryBatch(ctx interface{}, shopID interface{}, periods interface{}) *MetricsRepository_GetVisitsSummaryBatch_Call {
	return &MetricsRepository_GetVisitsSummaryBatch_Call{Call: _e.mock.On("GetVisitsSummaryBatch", ctx, shopID, periods)}
}

func (_c *MetricsRepository_GetVisitsSummaryBatch_Call) Run(run func(ctx context.Context, shopID int, periods []models.RevenuePeriod)) *MetricsRepository_GetVisitsSummaryBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []models.RevenuePeriod
		if args[2] != nil {
			arg2 = args[2].([]models.RevenuePeriod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetVisitsSummaryBatch_Call) Return(ints []int, err error) *MetricsRepository_GetVisitsSummaryBatch_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MetricsRepository_GetVisitsSummaryBatch_Call) RunAndReturn(run func(ctx context.Context, shopID int, periods []models.RevenuePeriod) ([]int, error)) *MetricsRepository_GetVisitsSummaryBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetVisitsTrend provides a mock function for the type MetricsRepository
func (_mock *MetricsRepository) GetVisitsTrend(ctx context.Context, shopID int, from time.Time, to time.Time, tz string) ([]models.VisitsTrendPoint, error) {
	ret := _mock.Called(ctx, shopID, from, to, tz)

	if len(ret) == 0 {
		panic("no return value specified for GetVisitsTrend")
	}

	var r0 []models.VisitsTrendPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time, string) ([]models.VisitsTrendPoint, error)); ok {
		return returnFunc(ctx, shopID, from, to, tz)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time, string) []models.VisitsTrendPoint); ok {
		r0 = returnFunc(ctx, shopID, from, to, tz)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.VisitsTrendPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time, string) error); ok {
		r1 = returnFunc(ctx, shopID, from, to, tz)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetricsRepository_GetVisitsTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVisitsTrend'
type MetricsRepository_GetVisitsTrend_Call struct {
	*mock.Call
}

// GetVisitsTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - from time.Time
//   - to time.Time
//   - tz string
func (_e *MetricsRepository_Expecter) GetVisitsTrend(ctx interface{}, shopID interface{}, from interface{}, to interface{}, tz interface{}) *MetricsRepository_GetVisitsTrend_Call {
	return &MetricsRepository_GetVisitsTrend_Call{Call: _e.mock.On("GetVisitsTrend", ctx, shopID, from, to, tz)}
}

func (_c *MetricsRepository_GetVisitsTrend_Call) Run(run func(ctx context.Context, shopID int, from time.Time, to time.Time, tz string)) *MetricsRepository_GetVisitsTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MetricsRepository_GetVisitsTrend_Call) Return(visitsTrendPoints []models.VisitsTrendPoint, err error) *MetricsRepository_GetVisitsTrend_Call {
	_c.Call.Return(visitsTrendPoints, err)
	return _c
}

func (_c *MetricsRepository_GetVisitsTrend_Call) RunAndReturn(run func(ctx context.Context, shopID int, from time.Time, to time.Time, tz string) ([]models.VisitsTrendPoint, error)) *MetricsRepository_GetVisitsTrend_Call {
	_c.Call.Return(run)
	return _c
}
