// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CountByShopIDWithFilters provides a mock function for the type OrderService
func (_mock *OrderService) CountByShopIDWithFilters(ctx context.Context, shopID int, filters models.OrderFilters) (int, error) {
	ret := _mock.Called(ctx, shopID, filters)

	if len(ret) == 0 {
		panic("no return value specified for CountByShopIDWithFilters")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.OrderFilters) (int, error)); ok {
		return returnFunc(ctx, shopID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.OrderFilters) int); ok {
		r0 = returnFunc(ctx, shopID, filters)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.OrderFilters) error); ok {
		r1 = returnFunc(ctx, shopID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_CountByShopIDWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByShopIDWithFilters'
type OrderService_CountByShopIDWithFilters_Call struct {
	*mock.Call
}

// CountByShopIDWithFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - filters models.OrderFilters
func (_e *OrderService_Expecter) CountByShopIDWithFilters(ctx interface{}, shopID interface{}, filters interface{}) *OrderService_CountByShopIDWithFilters_Call {
	return &OrderService_CountByShopIDWithFilters_Call{Call: _e.mock.On("CountByShopIDWithFilters", ctx, shopID, filters)}
}

func (_c *OrderService_CountByShopIDWithFilters_Call) Run(run func(ctx context.Context, shopID int, filters models.OrderFilters)) *OrderService_CountByShopIDWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.OrderFilters
		if args[2] != nil {
			arg2 = args[2].(models.OrderFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderService_CountByShopIDWithFilters_Call) Return(n int, err error) *OrderService_CountByShopIDWithFilters_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *OrderService_CountByShopIDWithFilters_Call) RunAndReturn(run func(ctx context.Context, shopID int, filters models.OrderFilters) (int, error)) *OrderService_CountByShopIDWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type OrderService
func (_mock *OrderService) Create(ctx context.Context, order *models.Order, store *models.Store) (*models.Order, error) {
	ret := _mock.Called(ctx, order, store)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Order, *models.Store) (*models.Order, error)); ok {
		return returnFunc(ctx, order, store)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Order, *models.Store) *models.Order); ok {
		r0 = returnFunc(ctx, order, store)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Order, *models.Store) error); ok {
		r1 = returnFunc(ctx, order, store)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *models.Order
//   - store *models.Store
func (_e *OrderService_Expecter) Create(ctx interface{}, order interface{}, store interface{}) *OrderService_Create_Call {
	return &OrderService_Create_Call{Call: _e.mock.On("Create", ctx, order, store)}
}

func (_c *OrderService_Create_Call) Run(run func(ctx context.Context, order *models.Order, store *models.Store)) *OrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Order
		if args[1] != nil {
			arg1 = args[1].(*models.Order)
		}
		var arg2 *models.Store
		if args[2] != nil {
			arg2 = args[2].(*models.Store)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderService_Create_Call) Return(order1 *models.Order, err error) *OrderService_Create_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *OrderService_Create_Call) RunAndReturn(run func(ctx context.Context, order *models.Order, store *models.Store) (*models.Order, error)) *OrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByShopIDWithFilters provides a mock function for the type OrderService
func (_mock *OrderService) GetAllByShopIDWithFilters(ctx context.Context, shopID int, filters models.OrderFilters) ([]*models.Order, error) {
	ret := _mock.Called(ctx, shopID, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByShopIDWithFilters")
	}

	var r0 []*models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.OrderFilters) ([]*models.Order, error)); ok {
		return returnFunc(ctx, shopID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.OrderFilters) []*models.Order); ok {
		r0 = returnFunc(ctx, shopID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.OrderFilters) error); ok {
		r1 = returnFunc(ctx, shopID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_GetAllByShopIDWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByShopIDWithFilters'
type OrderService_GetAllByShopIDWithFilters_Call struct {
	*mock.Call
}

// GetAllByShopIDWithFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - filters models.OrderFilters
func (_e *OrderService_Expecter) GetAllByShopIDWithFilters(ctx interface{}, shopID interface{}, filters interface{}) *OrderService_GetAllByShopIDWithFilters_Call {
	return &OrderService_GetAllByShopIDWithFilters_Call{Call: _e.mock.On("GetAllByShopIDWithFilters", ctx, shopID, filters)}
}

func (_c *OrderService_GetAllByShopIDWithFilters_Call) Run(run func(ctx context.Context, shopID int, filters models.OrderFilters)) *OrderService_GetAllByShopIDWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.OrderFilters
		if args[2] != nil {
			arg2 = args[2].(models.OrderFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderService_GetAllByShopIDWithFilters_Call) Return(orders []*models.Order, err error) *OrderService_GetAllByShopIDWithFilters_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *OrderService_GetAllByShopIDWithFilters_Call) RunAndReturn(run func(ctx context.Context, shopID int, filters models.OrderFilters) ([]*models.Order, error)) *OrderService_GetAllByShopIDWithFilters_Call {
	_c.Call.Return(run)
	return _c
}
