// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewPaymentMethodRepository creates a new instance of PaymentMethodRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentMethodRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentMethodRepository {
	mock := &PaymentMethodRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentMethodRepository is an autogenerated mock type for the PaymentMethodRepository type
type PaymentMethodRepository struct {
	mock.Mock
}

type PaymentMethodRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentMethodRepository) EXPECT() *PaymentMethodRepository_Expecter {
	return &PaymentMethodRepository_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type PaymentMethodRepository
func (_mock *PaymentMethodRepository) GetAll(ctx context.Context) ([]*models.PaymentMethod, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.PaymentMethod, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.PaymentMethod); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PaymentMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentMethodRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type PaymentMethodRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PaymentMethodRepository_Expecter) GetAll(ctx interface{}) *PaymentMethodRepository_GetAll_Call {
	return &PaymentMethodRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *PaymentMethodRepository_GetAll_Call) Run(run func(ctx context.Context)) *PaymentMethodRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PaymentMethodRepository_GetAll_Call) Return(paymentMethods []*models.PaymentMethod, err error) *PaymentMethodRepository_GetAll_Call {
	_c.Call.Return(paymentMethods, err)
	return _c
}

func (_c *PaymentMethodRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]*models.PaymentMethod, error)) *PaymentMethodRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function for the type PaymentMethodRepository
func (_mock *PaymentMethodRepository) GetByCode(ctx context.Context, code models.PaymentMethodCode) (*models.PaymentMethod, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *models.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.PaymentMethodCode) (*models.PaymentMethod, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.PaymentMethodCode) *models.PaymentMethod); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.PaymentMethodCode) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentMethodRepository_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type PaymentMethodRepository_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code models.PaymentMethodCode
func (_e *PaymentMethodRepository_Expecter) GetByCode(ctx interface{}, code interface{}) *PaymentMethodRepository_GetByCode_Call {
	return &PaymentMethodRepository_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *PaymentMethodRepository_GetByCode_Call) Run(run func(ctx context.Context, code models.PaymentMethodCode)) *PaymentMethodRepository_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.PaymentMethodCode
		if args[1] != nil {
			arg1 = args[1].(models.PaymentMethodCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentMethodRepository_GetByCode_Call) Return(paymentMethod *models.PaymentMethod, err error) *PaymentMethodRepository_GetByCode_Call {
	_c.Call.Return(paymentMethod, err)
	return _c
}

func (_c *PaymentMethodRepository_GetByCode_Call) RunAndReturn(run func(ctx context.Context, code models.PaymentMethodCode) (*models.PaymentMethod, error)) *PaymentMethodRepository_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type PaymentMethodRepository
func (_mock *PaymentMethodRepository) GetByID(ctx context.Context, id int) (*models.PaymentMethod, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.PaymentMethod, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.PaymentMethod); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentMethodRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PaymentMethodRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *PaymentMethodRepository_Expecter) GetByID(ctx interface{}, id interface{}) *PaymentMethodRepository_GetByID_Call {
	return &PaymentMethodRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *PaymentMethodRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *PaymentMethodRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentMethodRepository_GetByID_Call) Return(paymentMethod *models.PaymentMethod, err error) *PaymentMethodRepository_GetByID_Call {
	_c.Call.Return(paymentMethod, err)
	return _c
}

func (_c *PaymentMethodRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.PaymentMethod, error)) *PaymentMethodRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
