// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewProductHandler creates a new instance of ProductHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductHandler {
	mock := &ProductHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductHandler is an autogenerated mock type for the ProductHandler type
type ProductHandler struct {
	mock.Mock
}

type ProductHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductHandler) EXPECT() *ProductHandler_Expecter {
	return &ProductHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProductHandler
func (_mock *ProductHandler) Create(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// ProductHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProductHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *ProductHandler_Expecter) Create(responseWriter interface{}, request interface{}) *ProductHandler_Create_Call {
	return &ProductHandler_Create_Call{Call: _e.mock.On("Create", responseWriter, request)}
}

func (_c *ProductHandler_Create_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *ProductHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductHandler_Create_Call) Return() *ProductHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProductHandler_Create_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *ProductHandler_Create_Call {
	_c.Run(run)
	return _c
}

// GetAllByShopIDWithFilters provides a mock function for the type ProductHandler
func (_mock *ProductHandler) GetAllByShopIDWithFilters(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// ProductHandler_GetAllByShopIDWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByShopIDWithFilters'
type ProductHandler_GetAllByShopIDWithFilters_Call struct {
	*mock.Call
}

// GetAllByShopIDWithFilters is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *ProductHandler_Expecter) GetAllByShopIDWithFilters(responseWriter interface{}, request interface{}) *ProductHandler_GetAllByShopIDWithFilters_Call {
	return &ProductHandler_GetAllByShopIDWithFilters_Call{Call: _e.mock.On("GetAllByShopIDWithFilters", responseWriter, request)}
}

func (_c *ProductHandler_GetAllByShopIDWithFilters_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *ProductHandler_GetAllByShopIDWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductHandler_GetAllByShopIDWithFilters_Call) Return() *ProductHandler_GetAllByShopIDWithFilters_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProductHandler_GetAllByShopIDWithFilters_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *ProductHandler_GetAllByShopIDWithFilters_Call {
	_c.Run(run)
	return _c
}

// GetByID provides a mock function for the type ProductHandler
func (_mock *ProductHandler) GetByID(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// ProductHandler_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ProductHandler_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *ProductHandler_Expecter) GetByID(responseWriter interface{}, request interface{}) *ProductHandler_GetByID_Call {
	return &ProductHandler_GetByID_Call{Call: _e.mock.On("GetByID", responseWriter, request)}
}

func (_c *ProductHandler_GetByID_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *ProductHandler_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductHandler_GetByID_Call) Return() *ProductHandler_GetByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProductHandler_GetByID_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *ProductHandler_GetByID_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function for the type ProductHandler
func (_mock *ProductHandler) Update(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// ProductHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProductHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *ProductHandler_Expecter) Update(responseWriter interface{}, request interface{}) *ProductHandler_Update_Call {
	return &ProductHandler_Update_Call{Call: _e.mock.On("Update", responseWriter, request)}
}

func (_c *ProductHandler_Update_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *ProductHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductHandler_Update_Call) Return() *ProductHandler_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProductHandler_Update_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *ProductHandler_Update_Call {
	_c.Run(run)
	return _c
}
