// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewProductRepository creates a new instance of ProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepository {
	mock := &ProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

type ProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductRepository) EXPECT() *ProductRepository_Expecter {
	return &ProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProductRepository
func (_mock *ProductRepository) Create(ctx context.Context, product *models.Product, shopID int) (*models.Product, error) {
	ret := _mock.Called(ctx, product, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Product, int) (*models.Product, error)); ok {
		return returnFunc(ctx, product, shopID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Product, int) *models.Product); ok {
		r0 = returnFunc(ctx, product, shopID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Product, int) error); ok {
		r1 = returnFunc(ctx, product, shopID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product *models.Product
//   - shopID int
func (_e *ProductRepository_Expecter) Create(ctx interface{}, product interface{}, shopID interface{}) *ProductRepository_Create_Call {
	return &ProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, product, shopID)}
}

func (_c *ProductRepository_Create_Call) Run(run func(ctx context.Context, product *models.Product, shopID int)) *ProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Product
		if args[1] != nil {
			arg1 = args[1].(*models.Product)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *ProductRepository_Create_Call) Return(product *models.Product, err error) *ProductRepository_Create_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductRepository_Create_Call) RunAndReturn(run func(ctx context.Context, product *models.Product, shopID int) (*models.Product, error)) *ProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type ProductRepository
func (_mock *ProductRepository) GetByID(ctx context.Context, productID int) (*models.Product, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Product, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Product); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ProductRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID int
func (_e *ProductRepository_Expecter) GetByID(ctx interface{}, productID interface{}) *ProductRepository_GetByID_Call {
	return &ProductRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, productID)}
}

func (_c *ProductRepository_GetByID_Call) Run(run func(ctx context.Context, productID int)) *ProductRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *ProductRepository_GetByID_Call) Return(product *models.Product, err error) *ProductRepository_GetByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, productID int) (*models.Product, error)) *ProductRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProductRepository
func (_mock *ProductRepository) Update(ctx context.Context, productID int, product *models.Product) error {
	ret := _mock.Called(ctx, productID, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.Product) error); ok {
		r0 = returnFunc(ctx, productID, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - productID int
//   - product *models.Product
func (_e *ProductRepository_Expecter) Update(ctx interface{}, productID interface{}, product interface{}) *ProductRepository_Update_Call {
	return &ProductRepository_Update_Call{Call: _e.mock.On("Update", ctx, productID, product)}
}

func (_c *ProductRepository_Update_Call) Run(run func(ctx context.Context, productID int, product *models.Product)) *ProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.Product
		if args[2] != nil {
			arg2 = args[2].(*models.Product)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *ProductRepository_Update_Call) Return(err error) *ProductRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductRepository_Update_Call) RunAndReturn(run func(ctx context.Context, productID int, product *models.Product) error) *ProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByShopIDWithFilters provides a mock function for the type ProductRepository
func (_mock *ProductRepository) GetAllByShopIDWithFilters(ctx context.Context, filters models.ProductFilters) ([]*models.Product, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByShopIDWithFilters")
	}

	var r0 []*models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ProductFilters) ([]*models.Product, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ProductFilters) []*models.Product); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ProductFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductRepository_GetAllByShopIDWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByShopIDWithFilters'
type ProductRepository_GetAllByShopIDWithFilters_Call struct {
	*mock.Call
}

// GetAllByShopIDWithFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.ProductFilters
func (_e *ProductRepository_Expecter) GetAllByShopIDWithFilters(ctx interface{}, filters interface{}) *ProductRepository_GetAllByShopIDWithFilters_Call {
	return &ProductRepository_GetAllByShopIDWithFilters_Call{Call: _e.mock.On("GetAllByShopIDWithFilters", ctx, filters)}
}

func (_c *ProductRepository_GetAllByShopIDWithFilters_Call) Run(run func(ctx context.Context, filters models.ProductFilters)) *ProductRepository_GetAllByShopIDWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ProductFilters
		if args[1] != nil {
			arg1 = args[1].(models.ProductFilters)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *ProductRepository_GetAllByShopIDWithFilters_Call) Return(products []*models.Product, err error) *ProductRepository_GetAllByShopIDWithFilters_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *ProductRepository_GetAllByShopIDWithFilters_Call) RunAndReturn(run func(ctx context.Context, filters models.ProductFilters) ([]*models.Product, error)) *ProductRepository_GetAllByShopIDWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// CountByShopIDWithFilters provides a mock function for the type ProductRepository
func (_mock *ProductRepository) CountByShopIDWithFilters(ctx context.Context, filters models.ProductFilters) (int, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for CountByShopIDWithFilters")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ProductFilters) (int, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ProductFilters) int); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ProductFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductRepository_CountByShopIDWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByShopIDWithFilters'
type ProductRepository_CountByShopIDWithFilters_Call struct {
	*mock.Call
}

// CountByShopIDWithFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.ProductFilters
func (_e *ProductRepository_Expecter) CountByShopIDWithFilters(ctx interface{}, filters interface{}) *ProductRepository_CountByShopIDWithFilters_Call {
	return &ProductRepository_CountByShopIDWithFilters_Call{Call: _e.mock.On("CountByShopIDWithFilters", ctx, filters)}
}

func (_c *ProductRepository_CountByShopIDWithFilters_Call) Run(run func(ctx context.Context, filters models.ProductFilters)) *ProductRepository_CountByShopIDWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ProductFilters
		if args[1] != nil {
			arg1 = args[1].(models.ProductFilters)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *ProductRepository_CountByShopIDWithFilters_Call) Return(count int, err error) *ProductRepository_CountByShopIDWithFilters_Call {
	_c.Call.Return(count, err)
	return _c
}

func (_c *ProductRepository_CountByShopIDWithFilters_Call) RunAndReturn(run func(ctx context.Context, filters models.ProductFilters) (int, error)) *ProductRepository_CountByShopIDWithFilters_Call {
	_c.Call.Return(run)
	return _c
}
