// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewRemoveOrderCouponUseCase creates a new instance of RemoveOrderCouponUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoveOrderCouponUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoveOrderCouponUseCase {
	mock := &RemoveOrderCouponUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RemoveOrderCouponUseCase is an autogenerated mock type for the RemoveOrderCouponUseCase type
type RemoveOrderCouponUseCase struct {
	mock.Mock
}

type RemoveOrderCouponUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *RemoveOrderCouponUseCase) EXPECT() *RemoveOrderCouponUseCase_Expecter {
	return &RemoveOrderCouponUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type RemoveOrderCouponUseCase
func (_mock *RemoveOrderCouponUseCase) Execute(ctx context.Context, orderID int, shopID int) (*models.Order, error) {
	ret := _mock.Called(ctx, orderID, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*models.Order, error)); ok {
		return returnFunc(ctx, orderID, shopID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *models.Order); ok {
		r0 = returnFunc(ctx, orderID, shopID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, orderID, shopID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoveOrderCouponUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RemoveOrderCouponUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID int
//   - shopID int
func (_e *RemoveOrderCouponUseCase_Expecter) Execute(ctx interface{}, orderID interface{}, shopID interface{}) *RemoveOrderCouponUseCase_Execute_Call {
	return &RemoveOrderCouponUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, orderID, shopID)}
}

func (_c *RemoveOrderCouponUseCase_Execute_Call) Run(run func(ctx context.Context, orderID int, shopID int)) *RemoveOrderCouponUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RemoveOrderCouponUseCase_Execute_Call) Return(order *models.Order, err error) *RemoveOrderCouponUseCase_Execute_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *RemoveOrderCouponUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, orderID int, shopID int) (*models.Order, error)) *RemoveOrderCouponUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
