// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewRoleService creates a new instance of RoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleService {
	mock := &RoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleService is an autogenerated mock type for the RoleService type
type RoleService struct {
	mock.Mock
}

type RoleService_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleService) EXPECT() *RoleService_Expecter {
	return &RoleService_Expecter{mock: &_m.Mock}
}

// GetAllAssignable provides a mock function for the type RoleService
func (_mock *RoleService) GetAllAssignable(ctx context.Context) ([]*models.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssignable")
	}

	var r0 []*models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleService_GetAllAssignable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAssignable'
type RoleService_GetAllAssignable_Call struct {
	*mock.Call
}

// GetAllAssignable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RoleService_Expecter) GetAllAssignable(ctx interface{}) *RoleService_GetAllAssignable_Call {
	return &RoleService_GetAllAssignable_Call{Call: _e.mock.On("GetAllAssignable", ctx)}
}

func (_c *RoleService_GetAllAssignable_Call) Run(run func(ctx context.Context)) *RoleService_GetAllAssignable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RoleService_GetAllAssignable_Call) Return(roles []*models.Role, err error) *RoleService_GetAllAssignable_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *RoleService_GetAllAssignable_Call) RunAndReturn(run func(ctx context.Context) ([]*models.Role, error)) *RoleService_GetAllAssignable_Call {
	_c.Call.Return(run)
	return _c
}
