// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewRoleRepository creates a new instance of RoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleRepository {
	mock := &RoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleRepository is an autogenerated mock type for the RoleRepository type
type RoleRepository struct {
	mock.Mock
}

type RoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleRepository) EXPECT() *RoleRepository_Expecter {
	return &RoleRepository_Expecter{mock: &_m.Mock}
}

// GetAllAssignable provides a mock function for the type RoleRepository
func (_mock *RoleRepository) GetAllAssignable(ctx context.Context) ([]*models.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssignable")
	}

	var r0 []*models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_GetAllAssignable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAssignable'
type RoleRepository_GetAllAssignable_Call struct {
	*mock.Call
}

// GetAllAssignable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RoleRepository_Expecter) GetAllAssignable(ctx interface{}) *RoleRepository_GetAllAssignable_Call {
	return &RoleRepository_GetAllAssignable_Call{Call: _e.mock.On("GetAllAssignable", ctx)}
}

func (_c *RoleRepository_GetAllAssignable_Call) Run(run func(ctx context.Context)) *RoleRepository_GetAllAssignable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RoleRepository_GetAllAssignable_Call) Return(roles []*models.Role, err error) *RoleRepository_GetAllAssignable_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *RoleRepository_GetAllAssignable_Call) RunAndReturn(run func(ctx context.Context) ([]*models.Role, error)) *RoleRepository_GetAllAssignable_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type RoleRepository
func (_mock *RoleRepository) GetByID(ctx context.Context, id int) (*models.Role, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Role, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Role); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type RoleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *RoleRepository_Expecter) GetByID(ctx interface{}, id interface{}) *RoleRepository_GetByID_Call {
	return &RoleRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *RoleRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *RoleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleRepository_GetByID_Call) Return(role *models.Role, err error) *RoleRepository_GetByID_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *RoleRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Role, error)) *RoleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type RoleRepository
func (_mock *RoleRepository) GetByName(ctx context.Context, name string) (*models.Role, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Role, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Role); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type RoleRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *RoleRepository_Expecter) GetByName(ctx interface{}, name interface{}) *RoleRepository_GetByName_Call {
	return &RoleRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *RoleRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *RoleRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleRepository_GetByName_Call) Return(role *models.Role, err error) *RoleRepository_GetByName_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *RoleRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*models.Role, error)) *RoleRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}
