// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewRoleHandler creates a new instance of RoleHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleHandler {
	mock := &RoleHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleHandler is an autogenerated mock type for the RoleHandler type
type RoleHandler struct {
	mock.Mock
}

type RoleHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleHandler) EXPECT() *RoleHandler_Expecter {
	return &RoleHandler_Expecter{mock: &_m.Mock}
}

// GetAssignable provides a mock function for the type RoleHandler
func (_mock *RoleHandler) GetAssignable(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// RoleHandler_GetAssignable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssignable'
type RoleHandler_GetAssignable_Call struct {
	*mock.Call
}

// GetAssignable is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *RoleHandler_Expecter) GetAssignable(responseWriter interface{}, request interface{}) *RoleHandler_GetAssignable_Call {
	return &RoleHandler_GetAssignable_Call{Call: _e.mock.On("GetAssignable", responseWriter, request)}
}

func (_c *RoleHandler_GetAssignable_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *RoleHandler_GetAssignable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleHandler_GetAssignable_Call) Return() *RoleHandler_GetAssignable_Call {
	_c.Call.Return()
	return _c
}

func (_c *RoleHandler_GetAssignable_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *RoleHandler_GetAssignable_Call {
	_c.Run(run)
	return _c
}
