// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gorilla/mux"
	mock "github.com/stretchr/testify/mock"
)

// NewRouter creates a new instance of Router. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Router {
	mock := &Router{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Router is an autogenerated mock type for the Router type
type Router struct {
	mock.Mock
}

type Router_Expecter struct {
	mock *mock.Mock
}

func (_m *Router) EXPECT() *Router_Expecter {
	return &Router_Expecter{mock: &_m.Mock}
}

// RouteApp provides a mock function for the type Router
func (_mock *Router) RouteApp() *mux.Router {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RouteApp")
	}

	var r0 *mux.Router
	if returnFunc, ok := ret.Get(0).(func() *mux.Router); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mux.Router)
		}
	}
	return r0
}

// Router_RouteApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RouteApp'
type Router_RouteApp_Call struct {
	*mock.Call
}

// RouteApp is a helper method to define mock.On call
func (_e *Router_Expecter) RouteApp() *Router_RouteApp_Call {
	return &Router_RouteApp_Call{Call: _e.mock.On("RouteApp")}
}

func (_c *Router_RouteApp_Call) Run(run func()) *Router_RouteApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Router_RouteApp_Call) Return(router *mux.Router) *Router_RouteApp_Call {
	_c.Call.Return(router)
	return _c
}

func (_c *Router_RouteApp_Call) RunAndReturn(run func() *mux.Router) *Router_RouteApp_Call {
	_c.Call.Return(run)
	return _c
}
