// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewShopRepository creates a new instance of ShopRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShopRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShopRepository {
	mock := &ShopRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShopRepository is an autogenerated mock type for the ShopRepository type
type ShopRepository struct {
	mock.Mock
}

type ShopRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ShopRepository) EXPECT() *ShopRepository_Expecter {
	return &ShopRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ShopRepository
func (_mock *ShopRepository) Create(ctx context.Context, shop *models.Shop) (*models.Shop, error) {
	ret := _mock.Called(ctx, shop)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Shop
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Shop) (*models.Shop, error)); ok {
		return returnFunc(ctx, shop)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Shop) *models.Shop); ok {
		r0 = returnFunc(ctx, shop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Shop)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Shop) error); ok {
		r1 = returnFunc(ctx, shop)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShopRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ShopRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - shop *models.Shop
func (_e *ShopRepository_Expecter) Create(ctx interface{}, shop interface{}) *ShopRepository_Create_Call {
	return &ShopRepository_Create_Call{Call: _e.mock.On("Create", ctx, shop)}
}

func (_c *ShopRepository_Create_Call) Run(run func(ctx context.Context, shop *models.Shop)) *ShopRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Shop
		if args[1] != nil {
			arg1 = args[1].(*models.Shop)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShopRepository_Create_Call) Return(shop1 *models.Shop, err error) *ShopRepository_Create_Call {
	_c.Call.Return(shop1, err)
	return _c
}

func (_c *ShopRepository_Create_Call) RunAndReturn(run func(ctx context.Context, shop *models.Shop) (*models.Shop, error)) *ShopRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetShopsByUserID provides a mock function for the type ShopRepository
func (_mock *ShopRepository) GetShopsByUserID(ctx context.Context, userID int) ([]*models.Shop, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetShopsByUserID")
	}

	var r0 []*models.Shop
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Shop, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Shop); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Shop)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShopRepository_GetShopsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShopsByUserID'
type ShopRepository_GetShopsByUserID_Call struct {
	*mock.Call
}

// GetShopsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *ShopRepository_Expecter) GetShopsByUserID(ctx interface{}, userID interface{}) *ShopRepository_GetShopsByUserID_Call {
	return &ShopRepository_GetShopsByUserID_Call{Call: _e.mock.On("GetShopsByUserID", ctx, userID)}
}

func (_c *ShopRepository_GetShopsByUserID_Call) Run(run func(ctx context.Context, userID int)) *ShopRepository_GetShopsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShopRepository_GetShopsByUserID_Call) Return(shops []*models.Shop, err error) *ShopRepository_GetShopsByUserID_Call {
	_c.Call.Return(shops, err)
	return _c
}

func (_c *ShopRepository_GetShopsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*models.Shop, error)) *ShopRepository_GetShopsByUserID_Call {
	_c.Call.Return(run)
	return _c
}
