// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewSignUpService creates a new instance of SignUpService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignUpService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignUpService {
	mock := &SignUpService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SignUpService is an autogenerated mock type for the SignUpService type
type SignUpService struct {
	mock.Mock
}

type SignUpService_Expecter struct {
	mock *mock.Mock
}

func (_m *SignUpService) EXPECT() *SignUpService_Expecter {
	return &SignUpService_Expecter{mock: &_m.Mock}
}

// SignUp provides a mock function for the type SignUpService
func (_mock *SignUpService) SignUp(ctx context.Context, user *models.User, shop *models.Shop) (*models.User, error) {
	ret := _mock.Called(ctx, user, shop)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User, *models.Shop) (*models.User, error)); ok {
		return returnFunc(ctx, user, shop)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User, *models.Shop) *models.User); ok {
		r0 = returnFunc(ctx, user, shop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.User, *models.Shop) error); ok {
		r1 = returnFunc(ctx, user, shop)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SignUpService_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type SignUpService_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
//   - shop *models.Shop
func (_e *SignUpService_Expecter) SignUp(ctx interface{}, user interface{}, shop interface{}) *SignUpService_SignUp_Call {
	return &SignUpService_SignUp_Call{Call: _e.mock.On("SignUp", ctx, user, shop)}
}

func (_c *SignUpService_SignUp_Call) Run(run func(ctx context.Context, user *models.User, shop *models.Shop)) *SignUpService_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		var arg2 *models.Shop
		if args[2] != nil {
			arg2 = args[2].(*models.Shop)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SignUpService_SignUp_Call) Return(user1 *models.User, err error) *SignUpService_SignUp_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *SignUpService_SignUp_Call) RunAndReturn(run func(ctx context.Context, user *models.User, shop *models.Shop) (*models.User, error)) *SignUpService_SignUp_Call {
	_c.Call.Return(run)
	return _c
}
