// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewSignUpUseCase creates a new instance of SignUpUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignUpUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignUpUseCase {
	mock := &SignUpUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SignUpUseCase is an autogenerated mock type for the SignUpUseCase type
type SignUpUseCase struct {
	mock.Mock
}

type SignUpUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *SignUpUseCase) EXPECT() *SignUpUseCase_Expecter {
	return &SignUpUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type SignUpUseCase
func (_mock *SignUpUseCase) Execute(ctx context.Context, user *models.User, shop *models.Shop) error {
	ret := _mock.Called(ctx, user, shop)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User, *models.Shop) error); ok {
		r0 = returnFunc(ctx, user, shop)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SignUpUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type SignUpUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
//   - shop *models.Shop
func (_e *SignUpUseCase_Expecter) Execute(ctx interface{}, user interface{}, shop interface{}) *SignUpUseCase_Execute_Call {
	return &SignUpUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, user, shop)}
}

func (_c *SignUpUseCase_Execute_Call) Run(run func(ctx context.Context, user *models.User, shop *models.Shop)) *SignUpUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		var arg2 *models.Shop
		if args[2] != nil {
			arg2 = args[2].(*models.Shop)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SignUpUseCase_Execute_Call) Return(err error) *SignUpUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SignUpUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, user *models.User, shop *models.Shop) error) *SignUpUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
