// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewSignInUseCase creates a new instance of SignInUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignInUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignInUseCase {
	mock := &SignInUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SignInUseCase is an autogenerated mock type for the SignInUseCase type
type SignInUseCase struct {
	mock.Mock
}

type SignInUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *SignInUseCase) EXPECT() *SignInUseCase_Expecter {
	return &SignInUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type SignInUseCase
func (_mock *SignInUseCase) Execute(ctx context.Context, user *models.User) (string, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) (string, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) string); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SignInUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type SignInUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *SignInUseCase_Expecter) Execute(ctx interface{}, user interface{}) *SignInUseCase_Execute_Call {
	return &SignInUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, user)}
}

func (_c *SignInUseCase_Execute_Call) Run(run func(ctx context.Context, user *models.User)) *SignInUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SignInUseCase_Execute_Call) Return(s string, err error) *SignInUseCase_Execute_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *SignInUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, user *models.User) (string, error)) *SignInUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
