// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewSortable creates a new instance of Sortable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSortable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sortable {
	mock := &Sortable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Sortable is an autogenerated mock type for the Sortable type
type Sortable struct {
	mock.Mock
}

type Sortable_Expecter struct {
	mock *mock.Mock
}

func (_m *Sortable) EXPECT() *Sortable_Expecter {
	return &Sortable_Expecter{mock: &_m.Mock}
}

// GetSortValue provides a mock function for the type Sortable
func (_mock *Sortable) GetSortValue(sortBy string) interface{} {
	ret := _mock.Called(sortBy)

	if len(ret) == 0 {
		panic("no return value specified for GetSortValue")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(sortBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// Sortable_GetSortValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSortValue'
type Sortable_GetSortValue_Call struct {
	*mock.Call
}

// GetSortValue is a helper method to define mock.On call
//   - sortBy string
func (_e *Sortable_Expecter) GetSortValue(sortBy interface{}) *Sortable_GetSortValue_Call {
	return &Sortable_GetSortValue_Call{Call: _e.mock.On("GetSortValue", sortBy)}
}

func (_c *Sortable_GetSortValue_Call) Run(run func(sortBy string)) *Sortable_GetSortValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Sortable_GetSortValue_Call) Return(ifaceVal interface{}) *Sortable_GetSortValue_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *Sortable_GetSortValue_Call) RunAndReturn(run func(sortBy string) interface{}) *Sortable_GetSortValue_Call {
	_c.Call.Return(run)
	return _c
}
