// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewStaffHandler creates a new instance of StaffHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStaffHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *StaffHandler {
	mock := &StaffHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StaffHandler is an autogenerated mock type for the StaffHandler type
type StaffHandler struct {
	mock.Mock
}

type StaffHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *StaffHandler) EXPECT() *StaffHandler_Expecter {
	return &StaffHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type StaffHandler
func (_mock *StaffHandler) Create(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// StaffHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type StaffHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *StaffHandler_Expecter) Create(responseWriter interface{}, request interface{}) *StaffHandler_Create_Call {
	return &StaffHandler_Create_Call{Call: _e.mock.On("Create", responseWriter, request)}
}

func (_c *StaffHandler_Create_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StaffHandler_Create_Call) Return() *StaffHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *StaffHandler_Create_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_Create_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type StaffHandler
func (_mock *StaffHandler) Delete(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// StaffHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type StaffHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *StaffHandler_Expecter) Delete(responseWriter interface{}, request interface{}) *StaffHandler_Delete_Call {
	return &StaffHandler_Delete_Call{Call: _e.mock.On("Delete", responseWriter, request)}
}

func (_c *StaffHandler_Delete_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StaffHandler_Delete_Call) Return() *StaffHandler_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *StaffHandler_Delete_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_Delete_Call {
	_c.Run(run)
	return _c
}

// GetAll provides a mock function for the type StaffHandler
func (_mock *StaffHandler) GetAll(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// StaffHandler_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type StaffHandler_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *StaffHandler_Expecter) GetAll(responseWriter interface{}, request interface{}) *StaffHandler_GetAll_Call {
	return &StaffHandler_GetAll_Call{Call: _e.mock.On("GetAll", responseWriter, request)}
}

func (_c *StaffHandler_GetAll_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StaffHandler_GetAll_Call) Return() *StaffHandler_GetAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *StaffHandler_GetAll_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_GetAll_Call {
	_c.Run(run)
	return _c
}

// GetByID provides a mock function for the type StaffHandler
func (_mock *StaffHandler) GetByID(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// StaffHandler_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type StaffHandler_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *StaffHandler_Expecter) GetByID(responseWriter interface{}, request interface{}) *StaffHandler_GetByID_Call {
	return &StaffHandler_GetByID_Call{Call: _e.mock.On("GetByID", responseWriter, request)}
}

func (_c *StaffHandler_GetByID_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StaffHandler_GetByID_Call) Return() *StaffHandler_GetByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *StaffHandler_GetByID_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_GetByID_Call {
	_c.Run(run)
	return _c
}

// ToggleStatus provides a mock function for the type StaffHandler
func (_mock *StaffHandler) ToggleStatus(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// StaffHandler_ToggleStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleStatus'
type StaffHandler_ToggleStatus_Call struct {
	*mock.Call
}

// ToggleStatus is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *StaffHandler_Expecter) ToggleStatus(responseWriter interface{}, request interface{}) *StaffHandler_ToggleStatus_Call {
	return &StaffHandler_ToggleStatus_Call{Call: _e.mock.On("ToggleStatus", responseWriter, request)}
}

func (_c *StaffHandler_ToggleStatus_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_ToggleStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StaffHandler_ToggleStatus_Call) Return() *StaffHandler_ToggleStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *StaffHandler_ToggleStatus_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_ToggleStatus_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function for the type StaffHandler
func (_mock *StaffHandler) Update(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// StaffHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type StaffHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *StaffHandler_Expecter) Update(responseWriter interface{}, request interface{}) *StaffHandler_Update_Call {
	return &StaffHandler_Update_Call{Call: _e.mock.On("Update", responseWriter, request)}
}

func (_c *StaffHandler_Update_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StaffHandler_Update_Call) Return() *StaffHandler_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *StaffHandler_Update_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *StaffHandler_Update_Call {
	_c.Run(run)
	return _c
}
