// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/claims"
	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewStaffService creates a new instance of StaffService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStaffService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StaffService {
	mock := &StaffService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StaffService is an autogenerated mock type for the StaffService type
type StaffService struct {
	mock.Mock
}

type StaffService_Expecter struct {
	mock *mock.Mock
}

func (_m *StaffService) EXPECT() *StaffService_Expecter {
	return &StaffService_Expecter{mock: &_m.Mock}
}

// CountByShopIDWithFilters provides a mock function for the type StaffService
func (_mock *StaffService) CountByShopIDWithFilters(ctx context.Context, shopID int, filters models.StaffFilters) (int, error) {
	ret := _mock.Called(ctx, shopID, filters)

	if len(ret) == 0 {
		panic("no return value specified for CountByShopIDWithFilters")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.StaffFilters) (int, error)); ok {
		return returnFunc(ctx, shopID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.StaffFilters) int); ok {
		r0 = returnFunc(ctx, shopID, filters)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.StaffFilters) error); ok {
		r1 = returnFunc(ctx, shopID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StaffService_CountByShopIDWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByShopIDWithFilters'
type StaffService_CountByShopIDWithFilters_Call struct {
	*mock.Call
}

// CountByShopIDWithFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - filters models.StaffFilters
func (_e *StaffService_Expecter) CountByShopIDWithFilters(ctx interface{}, shopID interface{}, filters interface{}) *StaffService_CountByShopIDWithFilters_Call {
	return &StaffService_CountByShopIDWithFilters_Call{Call: _e.mock.On("CountByShopIDWithFilters", ctx, shopID, filters)}
}

func (_c *StaffService_CountByShopIDWithFilters_Call) Run(run func(ctx context.Context, shopID int, filters models.StaffFilters)) *StaffService_CountByShopIDWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.StaffFilters
		if args[2] != nil {
			arg2 = args[2].(models.StaffFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StaffService_CountByShopIDWithFilters_Call) Return(n int, err error) *StaffService_CountByShopIDWithFilters_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *StaffService_CountByShopIDWithFilters_Call) RunAndReturn(run func(ctx context.Context, shopID int, filters models.StaffFilters) (int, error)) *StaffService_CountByShopIDWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type StaffService
func (_mock *StaffService) Create(ctx context.Context, shopID int, user *models.User, roleID int, imageBuffer []byte) (*models.Staff, error) {
	ret := _mock.Called(ctx, shopID, user, roleID, imageBuffer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Staff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.User, int, []byte) (*models.Staff, error)); ok {
		return returnFunc(ctx, shopID, user, roleID, imageBuffer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.User, int, []byte) *models.Staff); ok {
		r0 = returnFunc(ctx, shopID, user, roleID, imageBuffer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Staff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *models.User, int, []byte) error); ok {
		r1 = returnFunc(ctx, shopID, user, roleID, imageBuffer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StaffService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type StaffService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - user *models.User
//   - roleID int
//   - imageBuffer []byte
func (_e *StaffService_Expecter) Create(ctx interface{}, shopID interface{}, user interface{}, roleID interface{}, imageBuffer interface{}) *StaffService_Create_Call {
	return &StaffService_Create_Call{Call: _e.mock.On("Create", ctx, shopID, user, roleID, imageBuffer)}
}

func (_c *StaffService_Create_Call) Run(run func(ctx context.Context, shopID int, user *models.User, roleID int, imageBuffer []byte)) *StaffService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.User
		if args[2] != nil {
			arg2 = args[2].(*models.User)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *StaffService_Create_Call) Return(staff *models.Staff, err error) *StaffService_Create_Call {
	_c.Call.Return(staff, err)
	return _c
}

func (_c *StaffService_Create_Call) RunAndReturn(run func(ctx context.Context, shopID int, user *models.User, roleID int, imageBuffer []byte) (*models.Staff, error)) *StaffService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type StaffService
func (_mock *StaffService) Delete(ctx context.Context, staffID int, shopID int) error {
	ret := _mock.Called(ctx, staffID, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, staffID, shopID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StaffService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type StaffService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int
//   - shopID int
func (_e *StaffService_Expecter) Delete(ctx interface{}, staffID interface{}, shopID interface{}) *StaffService_Delete_Call {
	return &StaffService_Delete_Call{Call: _e.mock.On("Delete", ctx, staffID, shopID)}
}

func (_c *StaffService_Delete_Call) Run(run func(ctx context.Context, staffID int, shopID int)) *StaffService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StaffService_Delete_Call) Return(err error) *StaffService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StaffService_Delete_Call) RunAndReturn(run func(ctx context.Context, staffID int, shopID int) error) *StaffService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByShopIDWithFilters provides a mock function for the type StaffService
func (_mock *StaffService) GetAllByShopIDWithFilters(ctx context.Context, shopID int, filters models.StaffFilters) ([]*models.Staff, error) {
	ret := _mock.Called(ctx, shopID, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByShopIDWithFilters")
	}

	var r0 []*models.Staff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.StaffFilters) ([]*models.Staff, error)); ok {
		return returnFunc(ctx, shopID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.StaffFilters) []*models.Staff); ok {
		r0 = returnFunc(ctx, shopID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Staff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.StaffFilters) error); ok {
		r1 = returnFunc(ctx, shopID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StaffService_GetAllByShopIDWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByShopIDWithFilters'
type StaffService_GetAllByShopIDWithFilters_Call struct {
	*mock.Call
}

// GetAllByShopIDWithFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - filters models.StaffFilters
func (_e *StaffService_Expecter) GetAllByShopIDWithFilters(ctx interface{}, shopID interface{}, filters interface{}) *StaffService_GetAllByShopIDWithFilters_Call {
	return &StaffService_GetAllByShopIDWithFilters_Call{Call: _e.mock.On("GetAllByShopIDWithFilters", ctx, shopID, filters)}
}

func (_c *StaffService_GetAllByShopIDWithFilters_Call) Run(run func(ctx context.Context, shopID int, filters models.StaffFilters)) *StaffService_GetAllByShopIDWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.StaffFilters
		if args[2] != nil {
			arg2 = args[2].(models.StaffFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StaffService_GetAllByShopIDWithFilters_Call) Return(staffs []*models.Staff, err error) *StaffService_GetAllByShopIDWithFilters_Call {
	_c.Call.Return(staffs, err)
	return _c
}

func (_c *StaffService_GetAllByShopIDWithFilters_Call) RunAndReturn(run func(ctx context.Context, shopID int, filters models.StaffFilters) ([]*models.Staff, error)) *StaffService_GetAllByShopIDWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type StaffService
func (_mock *StaffService) GetByID(ctx context.Context, staffID int, shopID int) (*models.Staff, error) {
	ret := _mock.Called(ctx, staffID, shopID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Staff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*models.Staff, error)); ok {
		return returnFunc(ctx, staffID, shopID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *models.Staff); ok {
		r0 = returnFunc(ctx, staffID, shopID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Staff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, staffID, shopID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StaffService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type StaffService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int
//   - shopID int
func (_e *StaffService_Expecter) GetByID(ctx interface{}, staffID interface{}, shopID interface{}) *StaffService_GetByID_Call {
	return &StaffService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, staffID, shopID)}
}

func (_c *StaffService_GetByID_Call) Run(run func(ctx context.Context, staffID int, shopID int)) *StaffService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StaffService_GetByID_Call) Return(staff *models.Staff, err error) *StaffService_GetByID_Call {
	_c.Call.Return(staff, err)
	return _c
}

func (_c *StaffService_GetByID_Call) RunAndReturn(run func(ctx context.Context, staffID int, shopID int) (*models.Staff, error)) *StaffService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetShopRolesByUserID provides a mock function for the type StaffService
func (_mock *StaffService) GetShopRolesByUserID(ctx context.Context, userID int) ([]claims.ShopRole, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetShopRolesByUserID")
	}

	var r0 []claims.ShopRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]claims.ShopRole, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []claims.ShopRole); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]claims.ShopRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StaffService_GetShopRolesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShopRolesByUserID'
type StaffService_GetShopRolesByUserID_Call struct {
	*mock.Call
}

// GetShopRolesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *StaffService_Expecter) GetShopRolesByUserID(ctx interface{}, userID interface{}) *StaffService_GetShopRolesByUserID_Call {
	return &StaffService_GetShopRolesByUserID_Call{Call: _e.mock.On("GetShopRolesByUserID", ctx, userID)}
}

func (_c *StaffService_GetShopRolesByUserID_Call) Run(run func(ctx context.Context, userID int)) *StaffService_GetShopRolesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StaffService_GetShopRolesByUserID_Call) Return(shopRoles []claims.ShopRole, err error) *StaffService_GetShopRolesByUserID_Call {
	_c.Call.Return(shopRoles, err)
	return _c
}

func (_c *StaffService_GetShopRolesByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]claims.ShopRole, error)) *StaffService_GetShopRolesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleStatus provides a mock function for the type StaffService
func (_mock *StaffService) ToggleStatus(ctx context.Context, staffID int, shopID int) (*models.Staff, error) {
	ret := _mock.Called(ctx, staffID, shopID)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 *models.Staff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*models.Staff, error)); ok {
		return returnFunc(ctx, staffID, shopID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *models.Staff); ok {
		r0 = returnFunc(ctx, staffID, shopID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Staff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, staffID, shopID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StaffService_ToggleStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleStatus'
type StaffService_ToggleStatus_Call struct {
	*mock.Call
}

// ToggleStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int
//   - shopID int
func (_e *StaffService_Expecter) ToggleStatus(ctx interface{}, staffID interface{}, shopID interface{}) *StaffService_ToggleStatus_Call {
	return &StaffService_ToggleStatus_Call{Call: _e.mock.On("ToggleStatus", ctx, staffID, shopID)}
}

func (_c *StaffService_ToggleStatus_Call) Run(run func(ctx context.Context, staffID int, shopID int)) *StaffService_ToggleStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StaffService_ToggleStatus_Call) Return(staff *models.Staff, err error) *StaffService_ToggleStatus_Call {
	_c.Call.Return(staff, err)
	return _c
}

func (_c *StaffService_ToggleStatus_Call) RunAndReturn(run func(ctx context.Context, staffID int, shopID int) (*models.Staff, error)) *StaffService_ToggleStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type StaffService
func (_mock *StaffService) Update(ctx context.Context, staffID int, shopID int, user *models.User, roleID int, imageBuffer []byte) (*models.Staff, error) {
	ret := _mock.Called(ctx, staffID, shopID, user, roleID, imageBuffer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Staff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *models.User, int, []byte) (*models.Staff, error)); ok {
		return returnFunc(ctx, staffID, shopID, user, roleID, imageBuffer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *models.User, int, []byte) *models.Staff); ok {
		r0 = returnFunc(ctx, staffID, shopID, user, roleID, imageBuffer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Staff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, *models.User, int, []byte) error); ok {
		r1 = returnFunc(ctx, staffID, shopID, user, roleID, imageBuffer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StaffService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type StaffService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int
//   - shopID int
//   - user *models.User
//   - roleID int
//   - imageBuffer []byte
func (_e *StaffService_Expecter) Update(ctx interface{}, staffID interface{}, shopID interface{}, user interface{}, roleID interface{}, imageBuffer interface{}) *StaffService_Update_Call {
	return &StaffService_Update_Call{Call: _e.mock.On("Update", ctx, staffID, shopID, user, roleID, imageBuffer)}
}

func (_c *StaffService_Update_Call) Run(run func(ctx context.Context, staffID int, shopID int, user *models.User, roleID int, imageBuffer []byte)) *StaffService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *models.User
		if args[3] != nil {
			arg3 = args[3].(*models.User)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 []byte
		if args[5] != nil {
			arg5 = args[5].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *StaffService_Update_Call) Return(staff *models.Staff, err error) *StaffService_Update_Call {
	_c.Call.Return(staff, err)
	return _c
}

func (_c *StaffService_Update_Call) RunAndReturn(run func(ctx context.Context, staffID int, shopID int, user *models.User, roleID int, imageBuffer []byte) (*models.Staff, error)) *StaffService_Update_Call {
	_c.Call.Return(run)
	return _c
}
