// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewStoreService creates a new instance of StoreService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreService {
	mock := &StoreService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StoreService is an autogenerated mock type for the StoreService type
type StoreService struct {
	mock.Mock
}

type StoreService_Expecter struct {
	mock *mock.Mock
}

func (_m *StoreService) EXPECT() *StoreService_Expecter {
	return &StoreService_Expecter{mock: &_m.Mock}
}

// GetBySlug provides a mock function for the type StoreService
func (_mock *StoreService) GetBySlug(ctx context.Context, slug string) (*models.Store, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *models.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Store, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Store); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreService_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type StoreService_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *StoreService_Expecter) GetBySlug(ctx interface{}, slug interface{}) *StoreService_GetBySlug_Call {
	return &StoreService_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *StoreService_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *StoreService_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreService_GetBySlug_Call) Return(store *models.Store, err error) *StoreService_GetBySlug_Call {
	_c.Call.Return(store, err)
	return _c
}

func (_c *StoreService_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*models.Store, error)) *StoreService_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}
