// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/claims"
	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenService creates a new instance of TokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenService {
	mock := &TokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

type TokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenService) EXPECT() *TokenService_Expecter {
	return &TokenService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type TokenService
func (_mock *TokenService) Generate(ctx context.Context, user *models.User, shopRoles []claims.ShopRole) (string, error) {
	ret := _mock.Called(ctx, user, shopRoles)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User, []claims.ShopRole) (string, error)); ok {
		return returnFunc(ctx, user, shopRoles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User, []claims.ShopRole) string); ok {
		r0 = returnFunc(ctx, user, shopRoles)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.User, []claims.ShopRole) error); ok {
		r1 = returnFunc(ctx, user, shopRoles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type TokenService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
//   - shopRoles []claims.ShopRole
func (_e *TokenService_Expecter) Generate(ctx interface{}, user interface{}, shopRoles interface{}) *TokenService_Generate_Call {
	return &TokenService_Generate_Call{Call: _e.mock.On("Generate", ctx, user, shopRoles)}
}

func (_c *TokenService_Generate_Call) Run(run func(ctx context.Context, user *models.User, shopRoles []claims.ShopRole)) *TokenService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		var arg2 []claims.ShopRole
		if args[2] != nil {
			arg2 = args[2].([]claims.ShopRole)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenService_Generate_Call) Return(s string, err error) *TokenService_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenService_Generate_Call) RunAndReturn(run func(ctx context.Context, user *models.User, shopRoles []claims.ShopRole) (string, error)) *TokenService_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAndParseClaims provides a mock function for the type TokenService
func (_mock *TokenService) ValidateAndParseClaims(token string) (*claims.TokenClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAndParseClaims")
	}

	var r0 *claims.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*claims.TokenClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *claims.TokenClaims); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*claims.TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenService_ValidateAndParseClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAndParseClaims'
type TokenService_ValidateAndParseClaims_Call struct {
	*mock.Call
}

// ValidateAndParseClaims is a helper method to define mock.On call
//   - token string
func (_e *TokenService_Expecter) ValidateAndParseClaims(token interface{}) *TokenService_ValidateAndParseClaims_Call {
	return &TokenService_ValidateAndParseClaims_Call{Call: _e.mock.On("ValidateAndParseClaims", token)}
}

func (_c *TokenService_ValidateAndParseClaims_Call) Run(run func(token string)) *TokenService_ValidateAndParseClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenService_ValidateAndParseClaims_Call) Return(tokenClaims *claims.TokenClaims, err error) *TokenService_ValidateAndParseClaims_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *TokenService_ValidateAndParseClaims_Call) RunAndReturn(run func(token string) (*claims.TokenClaims, error)) *TokenService_ValidateAndParseClaims_Call {
	_c.Call.Return(run)
	return _c
}
