// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewUpdateShopUseCase creates a new instance of UpdateShopUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateShopUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateShopUseCase {
	mock := &UpdateShopUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UpdateShopUseCase is an autogenerated mock type for the UpdateShopUseCase type
type UpdateShopUseCase struct {
	mock.Mock
}

type UpdateShopUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateShopUseCase) EXPECT() *UpdateShopUseCase_Expecter {
	return &UpdateShopUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type UpdateShopUseCase
func (_mock *UpdateShopUseCase) Execute(ctx context.Context, shopID int, shop *models.Shop, newLogoBuffer []byte, newCoverBuffer []byte) error {
	ret := _mock.Called(ctx, shopID, shop, newLogoBuffer, newCoverBuffer)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.Shop, []byte, []byte) error); ok {
		r0 = returnFunc(ctx, shopID, shop, newLogoBuffer, newCoverBuffer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UpdateShopUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UpdateShopUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - shop *models.Shop
//   - newLogoBuffer []byte
//   - newCoverBuffer []byte
func (_e *UpdateShopUseCase_Expecter) Execute(ctx interface{}, shopID interface{}, shop interface{}, newLogoBuffer interface{}, newCoverBuffer interface{}) *UpdateShopUseCase_Execute_Call {
	return &UpdateShopUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, shopID, shop, newLogoBuffer, newCoverBuffer)}
}

func (_c *UpdateShopUseCase_Execute_Call) Run(run func(ctx context.Context, shopID int, shop *models.Shop, newLogoBuffer []byte, newCoverBuffer []byte)) *UpdateShopUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.Shop
		if args[2] != nil {
			arg2 = args[2].(*models.Shop)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UpdateShopUseCase_Execute_Call) Return(err error) *UpdateShopUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UpdateShopUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, shopID int, shop *models.Shop, newLogoBuffer []byte, newCoverBuffer []byte) error) *UpdateShopUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
