// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewUpdateStaffUseCase creates a new instance of UpdateStaffUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateStaffUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateStaffUseCase {
	mock := &UpdateStaffUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UpdateStaffUseCase is an autogenerated mock type for the UpdateStaffUseCase type
type UpdateStaffUseCase struct {
	mock.Mock
}

type UpdateStaffUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateStaffUseCase) EXPECT() *UpdateStaffUseCase_Expecter {
	return &UpdateStaffUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type UpdateStaffUseCase
func (_mock *UpdateStaffUseCase) Execute(ctx context.Context, staffID int, shopID int, user *models.User, roleID int, imageBuffer []byte) (*models.Staff, error) {
	ret := _mock.Called(ctx, staffID, shopID, user, roleID, imageBuffer)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *models.Staff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *models.User, int, []byte) (*models.Staff, error)); ok {
		return returnFunc(ctx, staffID, shopID, user, roleID, imageBuffer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *models.User, int, []byte) *models.Staff); ok {
		r0 = returnFunc(ctx, staffID, shopID, user, roleID, imageBuffer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Staff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, *models.User, int, []byte) error); ok {
		r1 = returnFunc(ctx, staffID, shopID, user, roleID, imageBuffer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UpdateStaffUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UpdateStaffUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int
//   - shopID int
//   - user *models.User
//   - roleID int
//   - imageBuffer []byte
func (_e *UpdateStaffUseCase_Expecter) Execute(ctx interface{}, staffID interface{}, shopID interface{}, user interface{}, roleID interface{}, imageBuffer interface{}) *UpdateStaffUseCase_Execute_Call {
	return &UpdateStaffUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, staffID, shopID, user, roleID, imageBuffer)}
}

func (_c *UpdateStaffUseCase_Execute_Call) Run(run func(ctx context.Context, staffID int, shopID int, user *models.User, roleID int, imageBuffer []byte)) *UpdateStaffUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *models.User
		if args[3] != nil {
			arg3 = args[3].(*models.User)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 []byte
		if args[5] != nil {
			arg5 = args[5].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *UpdateStaffUseCase_Execute_Call) Return(staff *models.Staff, err error) *UpdateStaffUseCase_Execute_Call {
	_c.Call.Return(staff, err)
	return _c
}

func (_c *UpdateStaffUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, staffID int, shopID int, user *models.User, roleID int, imageBuffer []byte) (*models.Staff, error)) *UpdateStaffUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
