// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewUpdateCategoryUseCase creates a new instance of UpdateCategoryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateCategoryUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateCategoryUseCase {
	mock := &UpdateCategoryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UpdateCategoryUseCase is an autogenerated mock type for the UpdateCategoryUseCase type
type UpdateCategoryUseCase struct {
	mock.Mock
}

type UpdateCategoryUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateCategoryUseCase) EXPECT() *UpdateCategoryUseCase_Expecter {
	return &UpdateCategoryUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type UpdateCategoryUseCase
func (_mock *UpdateCategoryUseCase) Execute(ctx context.Context, categoryID int, category *models.Category, newImageBuffer []byte, shopID int) error {
	ret := _mock.Called(ctx, categoryID, category, newImageBuffer, shopID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.Category, []byte, int) error); ok {
		r0 = returnFunc(ctx, categoryID, category, newImageBuffer, shopID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UpdateCategoryUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UpdateCategoryUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID int
//   - category *models.Category
//   - newImageBuffer []byte
//   - shopID int
func (_e *UpdateCategoryUseCase_Expecter) Execute(ctx interface{}, categoryID interface{}, category interface{}, newImageBuffer interface{}, shopID interface{}) *UpdateCategoryUseCase_Execute_Call {
	return &UpdateCategoryUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, categoryID, category, newImageBuffer, shopID)}
}

func (_c *UpdateCategoryUseCase_Execute_Call) Run(run func(ctx context.Context, categoryID int, category *models.Category, newImageBuffer []byte, shopID int)) *UpdateCategoryUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.Category
		if args[2] != nil {
			arg2 = args[2].(*models.Category)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UpdateCategoryUseCase_Execute_Call) Return(err error) *UpdateCategoryUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UpdateCategoryUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, categoryID int, category *models.Category, newImageBuffer []byte, shopID int) error) *UpdateCategoryUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
