// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewUpdateOrderUseCase creates a new instance of UpdateOrderUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateOrderUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateOrderUseCase {
	mock := &UpdateOrderUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UpdateOrderUseCase is an autogenerated mock type for the UpdateOrderUseCase type
type UpdateOrderUseCase struct {
	mock.Mock
}

type UpdateOrderUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateOrderUseCase) EXPECT() *UpdateOrderUseCase_Expecter {
	return &UpdateOrderUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type UpdateOrderUseCase
func (_mock *UpdateOrderUseCase) Execute(ctx context.Context, shopID int, orderID int, updatedData *models.Order) (*models.Order, error) {
	ret := _mock.Called(ctx, shopID, orderID, updatedData)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *models.Order) (*models.Order, error)); ok {
		return returnFunc(ctx, shopID, orderID, updatedData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *models.Order) *models.Order); ok {
		r0 = returnFunc(ctx, shopID, orderID, updatedData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, *models.Order) error); ok {
		r1 = returnFunc(ctx, shopID, orderID, updatedData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UpdateOrderUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UpdateOrderUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID int
//   - orderID int
//   - updatedData *models.Order
func (_e *UpdateOrderUseCase_Expecter) Execute(ctx interface{}, shopID interface{}, orderID interface{}, updatedData interface{}) *UpdateOrderUseCase_Execute_Call {
	return &UpdateOrderUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, shopID, orderID, updatedData)}
}

func (_c *UpdateOrderUseCase_Execute_Call) Run(run func(ctx context.Context, shopID int, orderID int, updatedData *models.Order)) *UpdateOrderUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *models.Order
		if args[3] != nil {
			arg3 = args[3].(*models.Order)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UpdateOrderUseCase_Execute_Call) Return(order *models.Order, err error) *UpdateOrderUseCase_Execute_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *UpdateOrderUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, shopID int, orderID int, updatedData *models.Order) (*models.Order, error)) *UpdateOrderUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
