// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mlgaray/ecommerce_api/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewValidateStoreCouponUseCase creates a new instance of ValidateStoreCouponUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidateStoreCouponUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidateStoreCouponUseCase {
	mock := &ValidateStoreCouponUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ValidateStoreCouponUseCase is an autogenerated mock type for the ValidateStoreCouponUseCase type
type ValidateStoreCouponUseCase struct {
	mock.Mock
}

type ValidateStoreCouponUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *ValidateStoreCouponUseCase) EXPECT() *ValidateStoreCouponUseCase_Expecter {
	return &ValidateStoreCouponUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type ValidateStoreCouponUseCase
func (_mock *ValidateStoreCouponUseCase) Execute(ctx context.Context, storeSlug string, code string, phone string, subtotal float64) (*models.Coupon, error) {
	ret := _mock.Called(ctx, storeSlug, code, phone, subtotal)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *models.Coupon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, float64) (*models.Coupon, error)); ok {
		return returnFunc(ctx, storeSlug, code, phone, subtotal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, float64) *models.Coupon); ok {
		r0 = returnFunc(ctx, storeSlug, code, phone, subtotal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Coupon)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, float64) error); ok {
		r1 = returnFunc(ctx, storeSlug, code, phone, subtotal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ValidateStoreCouponUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ValidateStoreCouponUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - storeSlug string
//   - code string
//   - phone string
//   - subtotal float64
func (_e *ValidateStoreCouponUseCase_Expecter) Execute(ctx interface{}, storeSlug interface{}, code interface{}, phone interface{}, subtotal interface{}) *ValidateStoreCouponUseCase_Execute_Call {
	return &ValidateStoreCouponUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, storeSlug, code, phone, subtotal)}
}

func (_c *ValidateStoreCouponUseCase_Execute_Call) Run(run func(ctx context.Context, storeSlug string, code string, phone string, subtotal float64)) *ValidateStoreCouponUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 float64
		if args[4] != nil {
			arg4 = args[4].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ValidateStoreCouponUseCase_Execute_Call) Return(coupon *models.Coupon, err error) *ValidateStoreCouponUseCase_Execute_Call {
	_c.Call.Return(coupon, err)
	return _c
}

func (_c *ValidateStoreCouponUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, storeSlug string, code string, phone string, subtotal float64) (*models.Coupon, error)) *ValidateStoreCouponUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
