create table
    public.user_roles (
                          id bigint generated by default as identity not null,
                          created_at timestamp with time zone not null default now(),
                          user_id bigint not null,
                          role_id bigint not null,
                          constraint user_roles_pkey primary key (id),
                          constraint user_roles_id_key unique (id),
                          constraint user_roles_role_id_fkey foreign key (role_id) references roles (id) on update cascade on delete cascade,
                          constraint user_roles_user_id_fkey foreign key (user_id) references users (id) on update cascade on delete cascade
) tablespace pg_default;

CREATE INDEX idx_user_roles_user_id_role_id ON user_roles(user_id, role_id);
CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);

-- Enable Row Level Security (blocks REST API access without policies)
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
