create table public.product_images (
                                       id bigint generated by default as identity not null,
                                       url text null,
                                       product_id bigint not null,
                                       constraint product_images_pkey primary key (id),
                                       constraint product_images_id_key unique (id),
                                       constraint product_images_product_id_fkey foreign KEY (product_id) references products (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON public.product_images (product_id);