create table public.product_variants (
                                         id bigint generated by default as identity not null,
                                         name text not null,
                                         "order" bigint null,
                                         selection_type text null,
                                         max_selections bigint null,
                                         created_at timestamp with time zone not null default now(),
                                         product_id bigint not null,
                                         constraint product_variants_pkey primary key (id),
                                         constraint product_variants_product_id_fkey foreign KEY (product_id) references products (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON public.product_variants (product_id);