-- ============================================================================
-- TABLE: coupon_usages
-- Registro de uso de cupones vinculados a órdenes
-- ============================================================================
CREATE TABLE public.coupon_usages (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    -- Relaciones
    coupon_id bigint NOT NULL,
    order_id bigint NOT NULL,

    -- Datos de uso
    phone text NOT NULL,
    used_at timestamp with time zone NOT NULL DEFAULT now(),

    -- Constraints
    CONSTRAINT coupon_usages_pkey PRIMARY KEY (id),
    CONSTRAINT coupon_usages_coupon_id_fkey FOREIGN KEY (coupon_id)
        REFERENCES coupons (id) ON DELETE CASCADE,
    CONSTRAINT coupon_usages_order_id_fkey FOREIGN KEY (order_id)
        REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT coupon_usages_order_id_unique UNIQUE (order_id)
) TABLESPACE pg_default;

-- Indexes
CREATE INDEX idx_coupon_usages_coupon_id ON public.coupon_usages (coupon_id);
CREATE INDEX idx_coupon_usages_phone ON public.coupon_usages (phone);

-- Comments
COMMENT ON TABLE coupon_usages IS 'Registro de uso de cupones. Cada orden puede tener máximo un cupón (UNIQUE order_id).';
COMMENT ON COLUMN coupon_usages.phone IS 'Teléfono del cliente que usó el cupón. Para validar max_uses_per_phone.';

-- Enable Row Level Security
ALTER TABLE coupon_usages ENABLE ROW LEVEL SECURITY;
