-- Configuration for "delivery" type delivery methods
-- Contains fixed_price as alternative to zone-based pricing (delivery_zones)

create table
    public.delivery_configs (
                     id bigint generated by default as identity not null,
                     shop_delivery_method_id bigint not null,
                     fixed_price decimal(10,2) null,
                     created_at timestamp with time zone not null default now(),
                     updated_at timestamp with time zone not null default now(),
                     constraint delivery_configs_pkey primary key (id),
                     constraint delivery_configs_sdm_id_key unique (shop_delivery_method_id),
                     constraint delivery_configs_sdm_id_fkey foreign key (shop_delivery_method_id) references shop_delivery_methods (id) on update cascade on delete cascade
) tablespace pg_default;

CREATE INDEX IF NOT EXISTS idx_delivery_configs_sdm_id ON public.delivery_configs (shop_delivery_method_id);

COMMENT ON TABLE delivery_configs IS 'Configuration for delivery-type methods. If fixed_price is set, use it; otherwise use delivery_zones for zone-based pricing';
COMMENT ON COLUMN delivery_configs.fixed_price IS 'Fixed shipping price. NULL means use zone-based pricing from delivery_zones. 0 means free shipping.';

-- Enable Row Level Security (blocks REST API access without policies)
ALTER TABLE delivery_configs ENABLE ROW LEVEL SECURITY;
