create table
    public.shops (
                     id bigint generated by default as identity not null,
                     name text null,
                     user_id bigint not null,
                     created_at timestamp with time zone not null default now(),
                     email text null,
                     phone text null,
                     image text null,
                     instagram text null,
                     slug text null,
                     constraint businesses_pkey primary key (id),
                     constraint shops_email_key unique (email),
                     constraint businesses_user_id_fkey foreign key (user_id) references users (id) on update cascade on delete cascade
) tablespace pg_default;

CREATE INDEX IF NOT EXISTS idx_shops_user_id ON public.shops (user_id);
CREATE INDEX IF NOT EXISTS idx_shops_email ON public.shops (email);
CREATE INDEX IF NOT EXISTS idx_shops_slug ON public.shops (slug);