-- ============================================================================
-- TABLE: store_visits
-- Registra cada visita a una tienda (GET /stores/{slug}).
-- Append-only table para métricas de tráfico. Fire-and-forget desde el handler.
-- Retención recomendada: 90 días (purgar registros más antiguos periódicamente).
-- ============================================================================
CREATE TABLE public.store_visits (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shop_id bigint NOT NULL,
    visited_at timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT store_visits_pkey PRIMARY KEY (id),
    CONSTRAINT store_visits_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Index compuesto para consultas por tienda y rango de fechas (dashboard de métricas)
CREATE INDEX idx_store_visits_shop_visited ON public.store_visits (shop_id, visited_at DESC);

-- Index para purga eficiente de registros antiguos (retención)
CREATE INDEX idx_store_visits_visited_at ON public.store_visits (visited_at);

-- Comments
COMMENT ON TABLE store_visits IS 'Registra visitas a tiendas. Append-only, fire-and-forget. Retención: 90 días.';
COMMENT ON COLUMN store_visits.shop_id IS 'Tienda visitada';
COMMENT ON COLUMN store_visits.visited_at IS 'Momento de la visita (UTC)';
COMMENT ON INDEX idx_store_visits_shop_visited IS 'Consultas de visitas por tienda y rango temporal. Cubre el patrón: WHERE shop_id = ? AND visited_at BETWEEN ? AND ?';
COMMENT ON INDEX idx_store_visits_visited_at IS 'Purga eficiente de registros antiguos por fecha';

-- Row Level Security
ALTER TABLE store_visits ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- FUNCTION: purge_old_store_visits
-- Elimina registros de visitas más antiguos que el número de días especificado.
-- Uso: SELECT purge_old_store_visits(90);
-- Puede ejecutarse via pg_cron: SELECT cron.schedule('0 3 * * *', 'SELECT purge_old_store_visits(90)');
-- ============================================================================
CREATE OR REPLACE FUNCTION purge_old_store_visits(retention_days integer DEFAULT 90)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
    deleted_count bigint;
BEGIN
    DELETE FROM store_visits
    WHERE visited_at < now() - (retention_days || ' days')::interval;

    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$;

COMMENT ON FUNCTION purge_old_store_visits IS 'Purga visitas anteriores a retention_days días. Default: 90 días. Ejecutar periódicamente via pg_cron.';
