-- Operating schedules table
-- Stores business hours for shops, supporting split hours (multiple ranges per day)
-- Example: Monday 9:00-13:00 and 17:00-21:00

CREATE TABLE public.operating_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    day_of_week SMALLINT NOT NULL,  -- 0=Sunday, 1=Monday, ..., 6=Saturday (Go time.Weekday compatible)
    open_time TIME NOT NULL,
    close_time TIME NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Allows multiple ranges per day (morning and afternoon)
    CONSTRAINT operating_schedules_unique UNIQUE (shop_id, day_of_week, open_time),

    -- Validate that close > open
    CONSTRAINT operating_schedules_valid_range CHECK (close_time > open_time),

    -- Validate day_of_week is 0-6
    CONSTRAINT operating_schedules_valid_day CHECK (day_of_week >= 0 AND day_of_week <= 6),

    -- FK to shop
    CONSTRAINT operating_schedules_shop_fkey
        FOREIGN KEY (shop_id) REFERENCES shops(id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- Indexes for frequent queries
CREATE INDEX idx_operating_schedules_shop_id ON public.operating_schedules(shop_id);
CREATE INDEX idx_operating_schedules_day ON public.operating_schedules(shop_id, day_of_week);
