-- ============================================================================
-- TABLE: order_item_selected_options
-- Opciones de variantes seleccionadas para cada item
-- ============================================================================
CREATE TABLE public.order_item_selected_options (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_item_id bigint NOT NULL,

    -- Referencias originales (pueden ser NULL si fueron eliminadas)
    variant_id bigint NULL,
    option_id bigint NULL,

    -- Snapshot de la variante y opción
    variant_name text NOT NULL,
    option_name text NOT NULL,
    option_price double precision NOT NULL DEFAULT 0,

    -- Timestamp
    created_at timestamp with time zone NOT NULL DEFAULT now(),

    -- Constraints
    CONSTRAINT order_item_selected_options_pkey PRIMARY KEY (id),
    CONSTRAINT order_item_selected_options_order_item_id_fkey FOREIGN KEY (order_item_id)
        REFERENCES order_items (id) ON DELETE CASCADE,
    CONSTRAINT order_item_selected_options_variant_id_fkey FOREIGN KEY (variant_id)
        REFERENCES product_variants (id) ON DELETE SET NULL,
    CONSTRAINT order_item_selected_options_option_id_fkey FOREIGN KEY (option_id)
        REFERENCES variant_options (id) ON DELETE SET NULL,
    CONSTRAINT order_item_selected_options_price_not_negative CHECK (option_price >= 0)
) TABLESPACE pg_default;

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Obtener opciones de un item
CREATE INDEX idx_order_item_options_order_item_id
    ON public.order_item_selected_options (order_item_id);

-- Métricas: opciones más seleccionadas
CREATE INDEX idx_order_item_options_option_id
    ON public.order_item_selected_options (option_id)
    WHERE option_id IS NOT NULL;

-- Comentarios
COMMENT ON TABLE order_item_selected_options IS 'Opciones de variantes seleccionadas por el cliente. Una fila por cada opción. Snapshot para preservar datos históricos.';
COMMENT ON COLUMN order_item_selected_options.option_price IS 'Precio adicional de la opción al momento de la orden. Suma al unit_price del item.';

-- Enable Row Level Security
ALTER TABLE order_item_selected_options ENABLE ROW LEVEL SECURITY;
