create table
    public.options (
                       id bigint generated by default as identity not null,
                       name text null,
                       product_id bigint not null,
                       price double precision null,
                       created_at timestamp with time zone not null default now(),
                       constraint options_pkey primary key (id),
                       constraint options_id_key unique (id),
                       constraint options_product_id_fkey foreign key (product_id) references products (id) on update cascade on delete cascade
) tablespace pg_default;