create table users (
                              id bigint generated by default as identity not null,
                              name text not null,
                              last_name text not null,
                              email text not null,
                              phone bigint null,
                              password text not null,
                              is_active boolean null,
                              created_at timestamp with time zone not null default now(),
                              constraint users_pkey primary key (id),
                              constraint email_format check (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
                              constraint users_email_key unique (email)
) TABLESPACE pg_default;