-- ============================================================================
-- TABLE: order_item_selections
-- Variant and option selections for each order item.
-- One row per selected option. Snapshots preserve historical data.
-- ============================================================================
CREATE TABLE public.order_item_selections (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_item_id bigint NOT NULL,

    -- Referencias originales (pueden ser NULL si fueron eliminadas)
    variant_id bigint NULL,
    option_id bigint NULL,

    -- Snapshot de la variante y opción
    variant_name text NOT NULL,
    option_name text NOT NULL,
    option_price double precision NOT NULL DEFAULT 0,

    -- Timestamp
    created_at timestamp with time zone NOT NULL DEFAULT now(),

    -- Constraints
    CONSTRAINT order_item_selections_pkey PRIMARY KEY (id),
    CONSTRAINT order_item_selections_order_item_id_fkey FOREIGN KEY (order_item_id)
        REFERENCES order_items (id) ON DELETE CASCADE,
    CONSTRAINT order_item_selections_variant_id_fkey FOREIGN KEY (variant_id)
        REFERENCES product_variants (id) ON DELETE SET NULL,
    CONSTRAINT order_item_selections_option_id_fkey FOREIGN KEY (option_id)
        REFERENCES variant_options (id) ON DELETE SET NULL,
    CONSTRAINT order_item_selections_price_not_negative CHECK (option_price >= 0)
) TABLESPACE pg_default;

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Obtener opciones de un item
CREATE INDEX idx_order_item_selections_order_item_id
    ON public.order_item_selections (order_item_id);

-- Métricas: opciones más seleccionadas
CREATE INDEX idx_order_item_selections_option_id
    ON public.order_item_selections (option_id)
    WHERE option_id IS NOT NULL;

-- Variant analytics: which variants are most popular
CREATE INDEX idx_order_item_selections_variant_id
    ON public.order_item_selections (variant_id)
    WHERE variant_id IS NOT NULL;

-- Combined variant+option analytics
CREATE INDEX idx_order_item_selections_variant_option
    ON public.order_item_selections (variant_id, option_id)
    WHERE variant_id IS NOT NULL AND option_id IS NOT NULL;

-- Comentarios
COMMENT ON TABLE order_item_selections IS 'Variant and option selections for each order item. One row per selected option. Snapshots preserve historical data.';
COMMENT ON COLUMN order_item_selections.option_price IS 'Additional price of the option at order time. Adds to the item unit_price.';

-- Enable Row Level Security
ALTER TABLE order_item_selections ENABLE ROW LEVEL SECURITY;
