create table
    public.transfer_configs (
                     id bigint generated by default as identity not null,
                     shop_payment_method_id bigint not null,
                     cbu text not null,
                     cuil text not null,
                     alias text null,
                     owner_name text not null,
                     created_at timestamp with time zone not null default now(),
                     updated_at timestamp with time zone not null default now(),
                     constraint transfer_configs_pkey primary key (id),
                     constraint transfer_configs_spm_id_key unique (shop_payment_method_id),
                     constraint transfer_configs_spm_id_fkey foreign key (shop_payment_method_id) references shop_payment_methods (id) on update cascade on delete cascade
) tablespace pg_default;

CREATE INDEX IF NOT EXISTS idx_transfer_configs_spm_id ON public.transfer_configs (shop_payment_method_id);

-- Enable Row Level Security (blocks REST API access without policies)
ALTER TABLE transfer_configs ENABLE ROW LEVEL SECURITY;
