create table
    public.categories (
                          id bigint generated by default as identity,
                          name text null,
                          image text null,
                          created_at timestamp with time zone not null default now(),
                          shop_id bigint null,
                          constraint categories_pkey primary key (id),
                          constraint categories_id_key unique (id),
                          constraint categories_shop_id_fkey foreign key (shop_id) references shops (id) on update cascade on delete cascade
) tablespace pg_default;