create table
    public.pickup_configs (
                     id bigint generated by default as identity not null,
                     shop_delivery_method_id bigint not null,
                     address text not null,
                     city text not null,
                     province text null,
                     postal_code text null,
                     instructions text null,
                     created_at timestamp with time zone not null default now(),
                     updated_at timestamp with time zone not null default now(),
                     constraint pickup_configs_pkey primary key (id),
                     constraint pickup_configs_sdm_id_key unique (shop_delivery_method_id),
                     constraint pickup_configs_sdm_id_fkey foreign key (shop_delivery_method_id) references shop_delivery_methods (id) on update cascade on delete cascade
) tablespace pg_default;

CREATE INDEX IF NOT EXISTS idx_pickup_configs_sdm_id ON public.pickup_configs (shop_delivery_method_id);
