create table public.variant_options (
                                        id bigint generated by default as identity not null,
                                        name text null,
                                        price double precision null,
                                        "order" bigint null,
                                        variant_id bigint null,
                                        created_at timestamp with time zone not null default now(),
                                        constraint variant_options_pkey primary key (id),
                                        constraint variant_options_id_key unique (id),
                                        constraint variant_options_variant_id_fkey foreign KEY (variant_id) references product_variants (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_variant_options_variant_id ON public.variant_options (variant_id);