create table
    public.shops (
                     id bigint generated by default as identity not null,
                     name text null,
                     created_at timestamp with time zone not null default now(),
                     email text null,
                     phone text null,
                     instagram text null,
                     slug text null,
                     primary_color varchar(7) default '#8B5CF6',
                     constraint businesses_pkey primary key (id),
                     constraint shops_email_key unique (email)
) tablespace pg_default;

CREATE UNIQUE INDEX IF NOT EXISTS idx_shops_slug_unique ON public.shops (lower(slug)) WHERE slug IS NOT NULL;

-- Enable Row Level Security (blocks REST API access without policies)
ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
