CREATE TABLE
    public.roles (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                     NAME TEXT NULL,
                     description TEXT NULL,
                     CONSTRAINT roles_pkey PRIMARY KEY (id),
                     CONSTRAINT roles_id_key UNIQUE (id)
) TABLESPACE pg_default;

CREATE INDEX idx_roles_name ON public.roles (NAME);