create table
    public.payment_methods (
                     id bigint generated by default as identity not null,
                     name text not null,
                     code text not null,
                     description text null,
                     is_active boolean not null default true,
                     created_at timestamp with time zone not null default now(),
                     constraint payment_methods_pkey primary key (id),
                     constraint payment_methods_code_key unique (code)
) tablespace pg_default;

CREATE INDEX IF NOT EXISTS idx_payment_methods_code ON public.payment_methods (code);
CREATE INDEX IF NOT EXISTS idx_payment_methods_is_active ON public.payment_methods (is_active);
