-- ============================================================================
-- TABLE: order_items
-- Items de la orden con snapshot completo del producto
-- ============================================================================
CREATE TABLE public.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id bigint NOT NULL,

    -- Referencia al producto original (puede ser NULL si producto fue eliminado)
    product_id bigint NULL,

    -- Snapshot del producto al momento de la orden
    product_name text NOT NULL,
    product_image_url text NULL,
    base_price double precision NOT NULL,
    is_promotional boolean NOT NULL DEFAULT false,
    promotional_price double precision NULL,

    -- Cantidad y precios calculados
    quantity integer NOT NULL DEFAULT 1,
    unit_price double precision NOT NULL,
    total_price double precision NOT NULL,

    -- Timestamp de cuando se agregó el item
    added_at timestamp with time zone NOT NULL DEFAULT now(),

    -- Constraints
    CONSTRAINT order_items_pkey PRIMARY KEY (id),
    CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
        REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id)
        REFERENCES products (id) ON DELETE SET NULL,
    CONSTRAINT order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_items_base_price_positive CHECK (base_price >= 0),
    CONSTRAINT order_items_unit_price_positive CHECK (unit_price >= 0),
    CONSTRAINT order_items_total_price_positive CHECK (total_price >= 0)
) TABLESPACE pg_default;

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Obtener items de una orden
CREATE INDEX idx_order_items_order_id ON public.order_items (order_id);

-- Métricas de productos más vendidos
CREATE INDEX idx_order_items_product_id ON public.order_items (product_id)
    WHERE product_id IS NOT NULL;

-- Product sales analytics: which products sell most in a period
CREATE INDEX idx_order_items_product_added ON public.order_items (product_id, added_at DESC)
    WHERE product_id IS NOT NULL;

-- Promotional items tracking
CREATE INDEX idx_order_items_promotional ON public.order_items (added_at DESC)
    WHERE is_promotional = true;

-- Comentarios
COMMENT ON TABLE order_items IS 'Items de la orden. Snapshot completo del producto para preservar datos históricos independiente de cambios en el catálogo.';
COMMENT ON COLUMN order_items.unit_price IS 'Precio efectivo por unidad: precio base o promocional + suma de opciones seleccionadas.';
COMMENT ON COLUMN order_items.product_id IS 'FK al producto. SET NULL si el producto es eliminado. El snapshot preserva los datos.';

-- Enable Row Level Security
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
