-- Tabla images unificada con Exclusive Belongs-To pattern
-- Soporta imágenes para: Category, Product, User, Shop
CREATE TABLE public.images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL,
    storage_ref text NOT NULL DEFAULT '',
    created_at timestamptz DEFAULT now(),

    -- FK nullables (una por entidad)
    category_id bigint REFERENCES categories(id) ON DELETE CASCADE,
    product_id bigint REFERENCES products(id) ON DELETE CASCADE,
    user_id bigint REFERENCES users(id) ON DELETE CASCADE,
    shop_id bigint REFERENCES shops(id) ON DELETE CASCADE,

    -- Garantiza exactamente una FK activa
    CONSTRAINT images_single_entity CHECK (
        num_nonnulls(category_id, product_id, user_id, shop_id) = 1
    )
) TABLESPACE pg_default;

-- Índices parciales (eficientes, solo indexan filas relevantes)
CREATE INDEX idx_images_category ON images(category_id) WHERE category_id IS NOT NULL;
CREATE INDEX idx_images_product ON images(product_id) WHERE product_id IS NOT NULL;
CREATE INDEX idx_images_user ON images(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_images_shop ON images(shop_id) WHERE shop_id IS NOT NULL;
