create table
    public.mercadopago_configs (
                     id bigint generated by default as identity not null,
                     shop_payment_method_id bigint not null,
                     access_token text not null,
                     public_key text not null,
                     user_id text null,
                     created_at timestamp with time zone not null default now(),
                     updated_at timestamp with time zone not null default now(),
                     constraint mercadopago_configs_pkey primary key (id),
                     constraint mercadopago_configs_spm_id_key unique (shop_payment_method_id),
                     constraint mercadopago_configs_spm_id_fkey foreign key (shop_payment_method_id) references shop_payment_methods (id) on update cascade on delete cascade
) tablespace pg_default;

CREATE INDEX IF NOT EXISTS idx_mercadopago_configs_spm_id ON public.mercadopago_configs (shop_payment_method_id);
