-- Staff: vincula usuario a tienda con estado
CREATE TABLE public.staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    shop_id bigint NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT staff_shop_user_unique UNIQUE (shop_id, user_id)
);
CREATE INDEX idx_staff_user_id ON staff(user_id);
CREATE INDEX idx_staff_shop_id ON staff(shop_id);

-- Staff Roles: roles contextuales por staff member
CREATE TABLE public.staff_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
    role_id bigint NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT staff_roles_unique UNIQUE (staff_id, role_id)
);
CREATE INDEX idx_staff_roles_staff_id ON staff_roles(staff_id);

-- Permissions: acciones granulares
CREATE TABLE public.permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    description text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Role Permissions: qué permisos tiene cada rol
CREATE TABLE public.role_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id bigint NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id bigint NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    CONSTRAINT role_permissions_unique UNIQUE (role_id, permission_id)
);
CREATE INDEX idx_role_permissions_role_id ON role_permissions(role_id);
