-- ============================================================================
-- TABLE: orders
-- Orden principal del sistema de e-commerce
-- ============================================================================
CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    -- Número de orden legible (secuencial por store)
    order_number text NOT NULL,

    -- Store (FK requerida, apunta a shops.id)
    store_id bigint NOT NULL,
    store_name text NOT NULL,
    store_slug text NOT NULL,

    -- Estado
    status text NOT NULL DEFAULT 'draft',

    -- Cliente (embebido, incluye dirección de entrega)
    customer_name text NOT NULL,
    customer_phone text NULL,
    customer_email text NULL,
    customer_address_name text NULL,
    customer_address_place_id text NULL,
    customer_address_lat double precision NULL,
    customer_address_lng double precision NULL,

    -- Método de pago (snapshot)
    payment_method_id bigint NULL,
    payment_method_code text NULL,
    payment_method_name text NULL,

    -- Método de entrega (snapshot)
    delivery_method_id bigint NULL,
    delivery_method_code text NULL,
    delivery_method_name text NULL,

    -- Totales
    subtotal double precision NOT NULL DEFAULT 0,
    shipping_cost double precision NOT NULL DEFAULT 0,
    total double precision NOT NULL DEFAULT 0,

    -- Timestamps
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),

    -- Constraints
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_store_id_fkey FOREIGN KEY (store_id)
        REFERENCES shops (id) ON DELETE RESTRICT,
    CONSTRAINT orders_payment_method_id_fkey FOREIGN KEY (payment_method_id)
        REFERENCES payment_methods (id) ON DELETE SET NULL,
    CONSTRAINT orders_delivery_method_id_fkey FOREIGN KEY (delivery_method_id)
        REFERENCES delivery_methods (id) ON DELETE SET NULL,
    CONSTRAINT orders_status_check CHECK (
        status IN ('draft', 'pending', 'confirmed', 'completed', 'cancelled')
    ),
    CONSTRAINT orders_order_number_store_unique UNIQUE (store_id, order_number)
) TABLESPACE pg_default;

-- ============================================================================
-- INDEXES: Optimizados para métricas y consultas frecuentes
-- ============================================================================

-- Listado de órdenes por store
CREATE INDEX idx_orders_store_id ON public.orders (store_id);

-- Filtrado por estado
CREATE INDEX idx_orders_status ON public.orders (status);

-- Métricas de ventas por período
CREATE INDEX idx_orders_store_created_at ON public.orders (store_id, created_at DESC);

-- Dashboard: órdenes por store y estado ordenadas por fecha
CREATE INDEX idx_orders_store_status_created ON public.orders (store_id, status, created_at DESC);

-- Métricas por método de pago
CREATE INDEX idx_orders_payment_method_id ON public.orders (payment_method_id);

-- Métricas por método de entrega
CREATE INDEX idx_orders_delivery_method_id ON public.orders (delivery_method_id);

-- Búsqueda por cliente (email)
CREATE INDEX idx_orders_customer_email ON public.orders (customer_email)
    WHERE customer_email IS NOT NULL;

-- Comentarios de documentación
COMMENT ON TABLE orders IS 'Órdenes del sistema. Contiene snapshots desnormalizados de store, cliente, dirección y métodos para preservar datos históricos.';
COMMENT ON COLUMN orders.status IS 'Estados: draft (borrador), pending (pendiente), confirmed (confirmada), completed (completada), cancelled (cancelada)';
COMMENT ON COLUMN orders.subtotal IS 'Suma de order_items.total_price. Calculado y almacenado para performance.';
COMMENT ON COLUMN orders.total IS 'subtotal + shipping_cost. Almacenado para evitar recálculos.';

-- Enable Row Level Security
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
