DROP FUNCTION IF EXISTS update_shop(
    INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT,
    JSONB, JSONB, JSONB, JSONB, JSONB
);

DROP FUNCTION IF EXISTS update_shop(
    INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT,
    JSONB, JSONB, JSONB, JSONB, JSONB
);
